license_finder permitted_licenses add "Apache 2.0"
license_finder permitted_licenses add "New BSD"
license_finder permitted_licenses add "Simplified BSD"
license_finder permitted_licenses add "MIT"
license_finder permitted_licenses add "Mozilla Public License 2.0"
license_finder permitted_licenses add "ISC"
license_finder licenses add ./internal/signalfx-agent "Apache 2.0"
license_finder licenses add ./pkg/extension/smartagentextension "Apache 2.0"
license_finder licenses add ./pkg/processor/timestampprocessor "Apache 2.0"
license_finder licenses add ./pkg/receiver/smartagentreceiver "Apache 2.0"
license_finder licenses add github.com/Showmax/go-fqdn "Apache 2.0"
license_finder licenses add github.com/Showmax/go-fqdn "Simplified BSD"
license_finder licenses add github.com/Showmax/go-fqdn "Apache 2.0"
license_finder licenses add github.com/beevik/ntp "Simplified BSD"
license_finder licenses add github.com/hashicorp/consul/api "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-kms-wrapping/v2 "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-plugin "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-retryablehttp "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-secure-stdlib/awsutil "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-secure-stdlib/cryptoutil "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-secure-stdlib/mlock "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-secure-stdlib/parseutil "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-secure-stdlib/permitpool "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-secure-stdlib/plugincontainer "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-secure-stdlib/regexp "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-uuid "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/golang-lru "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/nomad/api "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/vault-plugin-auth-gcp "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/vault/api "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/vault/sdk "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/yamux "Mozilla Public License 2.0"
license_finder licenses add github.com/jmespath/go-jmespath "Apache 2.0"
license_finder licenses add github.com/rcrowley/go-metrics "Simplified BSD"
license_finder licenses add github.com/hashicorp/go-gcp-common "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-version "Mozilla Public License 2.0"
license_finder licenses add github.com/hashicorp/go-kms-wrapping/entropy/v2 "Mozilla Public License 2.0"
