// Code generated by monitor-code-gen. DO NOT EDIT.

package winservices

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "telegraf/win_services"

var groupSet = map[string]bool{}

const (
	winServicesStartupMode = "win_services.startup_mode"
	winServicesState       = "win_services.state"
)

var metricSet = map[string]monitors.MetricInfo{
	winServicesStartupMode: {Type: datapoint.Gauge},
	winServicesState:       {Type: datapoint.Gauge},
}

var defaultMetrics = map[string]bool{}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "telegraf/win_services",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         true,
}
