type: "signalfxgatewayprometheusremotewrite"

status:
  class: "receiver"
  stability:
    deprecated: ["metrics"]
  deprecation:
    metrics:
      date: "2026-03-18"
      migration: "No migration path is provided. Support for this receiver is ending and it will be removed in a future release."
  distributions: ["splunk"]
  codeowners:
    active: ["hughesjj"]
