type: "signalfxgatewayprometheusremotewrite"

status:
  class: "receiver"
  stability:
    deprecated: ["metrics"]
  deprecation:
    metrics:
      date: "2026-03-18"
      migration: "No supported migration path is provided. This ends support for the receiver, and its removal will be a breaking change. Update your configuration accordingly."
  distributions: ["splunk"]
  codeowners:
    active: ["hughesjj"]
