# A centos9 image with systemd enabled.  Must be run with:
# `-d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro` flags
FROM tomcat:9-jre8 as tomcat

FROM quay.io/centos/centos:stream9

ENV container docker

RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
RUN echo 'fastestmirror=1' >> /etc/yum.conf
RUN dnf install -y procps initscripts systemd wget

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

COPY --from=tomcat /usr/local/tomcat /usr/local/tomcat
COPY --from=tomcat /opt/java /opt/java
COPY instrumentation/setup-tomcat.sh /opt/
RUN bash /opt/setup-tomcat.sh

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
