FROM ubuntu:22.04

RUN apt-get update &&\
    apt-get install -yq ca-certificates procps systemd wget apt-transport-https libcap2-bin curl gnupg lsb-release

ARG PUPPET_RELEASE="6"
RUN wget https://apt.puppetlabs.com/puppet${PUPPET_RELEASE}-release-jammy.deb && \
    dpkg -i puppet${PUPPET_RELEASE}-release-jammy.deb && \
    apt-get update && \
    apt-get install -y puppet-agent

RUN wget -O /tmp/nodejs.tar.gz https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.gz && \
    mkdir -p /opt/local-repo && \
    tar -C /opt/ -xzf /tmp/nodejs.tar.gz && \
    mv /opt/node* /opt/node

ENV PATH=/opt/puppetlabs/bin:/opt/node/bin:$PATH

ENV container=docker

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/systemd-update-utmp*

RUN systemctl set-default multi-user.target
ENV init=/lib/systemd/systemd

RUN if [ $PUPPET_RELEASE -lt 8 ]; then \
      puppet module install puppetlabs-stdlib --version 4.24.0 && \
      puppet module install puppetlabs-apt --version 7.0.0; \
    else \
      puppet module install puppetlabs-stdlib --version 9.0.0 && \
      puppet module install puppetlabs-apt --version 9.1.0; \
    fi

COPY deployments/puppet /etc/puppetlabs/code/environments/production/modules/splunk_otel_collector

COPY dist/* /opt/local-repo/
RUN chmod -R a+rwX /opt/local-repo/

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT ["/lib/systemd/systemd"]
