#!/bin/bash

# Copyright Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Set the rpath on all binaries to point to the $root/lib directory, using a
# relative path from $ORIGIN.

set -euo pipefail

root=${1}

echo "Using final root directory of $root"

cd $root

for f in $(find bin lib jre -type f -executable -or -name "*.so*"); do
  existing_rpath=$(patchelf --print-rpath $f 2>/dev/null || true)
  patchelf --set-rpath '$ORIGIN/'$(/usr/bin/realpath --relative-to $(dirname $f) ${root%/}/lib):$existing_rpath $f 2>/dev/null || true
done
