#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_DIR="$( cd "$SCRIPT_DIR"/../../ && pwd )"
CUR_DIR="$PWD"

OTEL_VERSION="${OTEL_VERSION:-main}"
CORE_VERSION="${CORE_VERSION:-$OTEL_VERSION}"
CONTRIB_VERSION="${CONTRIB_VERSION:-$OTEL_VERSION}"

CORE_PKGS="go.opentelemetry.io/collector"
CONTRIB_PKGS="github.com/open-telemetry/opentelemetry-collector-contrib"

trap "cd $CUR_DIR" EXIT

for gomod in $( find "$REPO_DIR" -name "go.mod" | grep -v "/examples/" | sort ); do
    pushd "$( dirname "$gomod" )" >/dev/null

    if grep -q "^[[:space:]]\+${CORE_PKGS}/" go.mod; then
        echo "Updating ${CORE_PKGS}/... in $gomod to $CORE_VERSION"
        go get ${CORE_PKGS}/...@${CORE_VERSION}
    fi

    if grep -q "^[[:space:]]\+${CONTRIB_PKGS}/" go.mod; then
        echo "Updating ${CONTRIB_PKGS}/... in $gomod to $CONTRIB_VERSION"
        go get ${CONTRIB_PKGS}/...@${CONTRIB_VERSION}
    fi

    [ -f Makefile ] && make tidy

    popd >/dev/null
done

make -C "$REPO_DIR" for-all CMD='make tidy'
