// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/rollingspanlatency component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("rollingspanlatency")
	ScopeName = "github.com/signalfx/splunk-otel-collector/pkg/processor/rollingspanlatencyprocessor"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
