//go:build linux
// +build linux

package cpufreq

// AUTOGENERATED BY scripts/collectd-template-to-go.  DO NOT EDIT!!

import (
	"text/template"

	"github.com/signalfx/signalfx-agent/pkg/monitors/collectd"
)

// CollectdTemplate is a template for a cpufreq collectd config file
var CollectdTemplate = template.Must(collectd.InjectTemplateFuncs(template.New("cpufreq")).Parse(`
LoadPlugin cpufreq

<Chain "PostCache"> 
  <Rule "set_cpufreq_monitor_id"> 
    <Match "regex"> 
      Plugin "^cpufreq$" 
    </Match> 
    <Target "set"> 
      MetaData "monitorID" "{{.MonitorID}}" 
    </Target> 
  </Rule> 
</Chain>
`)).Option("missingkey=error")
