//go:build linux
// +build linux

package protocols

// AUTOGENERATED BY scripts/collectd-template-to-go.  DO NOT EDIT!!

import (
	"text/template"

	"github.com/signalfx/signalfx-agent/pkg/monitors/collectd"
)

// CollectdTemplate is a template for a protocols collectd config file
var CollectdTemplate = template.Must(collectd.InjectTemplateFuncs(template.New("protocols")).Parse(`
LoadPlugin protocols
<Plugin "protocols">
  Value "Icmp:InDestUnreachs"
  Value "Tcp:CurrEstab"
  Value "Tcp:OutSegs"
  Value "Tcp:RetransSegs"
  Value "TcpExt:DelayedACKs"
  Value "/Tcp:.*Opens/"
  Value "/^TcpExt:.*Octets/"
  IgnoreSelected false
</Plugin>

<Chain "PostCache"> 
  <Rule "set_protocols_monitor_id"> 
    <Match "regex"> 
      Plugin "^protocols$" 
    </Match> 
    <Target "set"> 
      MetaData "monitorID" "{{.MonitorID}}" 
    </Target> 
  </Rule> 
</Chain>
`)).Option("missingkey=error")
