// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms, confmap.WithErrorUnused())
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for databricks metrics.
type MetricsConfig struct {
	DatabricksJobsActiveTotal                                                                                          MetricConfig `mapstructure:"databricks.jobs.active.total"`
	DatabricksJobsRunDuration                                                                                          MetricConfig `mapstructure:"databricks.jobs.run.duration"`
	DatabricksJobsScheduleStatus                                                                                       MetricConfig `mapstructure:"databricks.jobs.schedule.status"`
	DatabricksJobsTotal                                                                                                MetricConfig `mapstructure:"databricks.jobs.total"`
	DatabricksSparkBlockManagerMemoryDiskSpaceUsed                                                                     MetricConfig `mapstructure:"databricks.spark.block_manager.memory.disk_space.used"`
	DatabricksSparkBlockManagerMemoryMax                                                                               MetricConfig `mapstructure:"databricks.spark.block_manager.memory.max"`
	DatabricksSparkBlockManagerMemoryOffHeapMax                                                                        MetricConfig `mapstructure:"databricks.spark.block_manager.memory.off_heap.max"`
	DatabricksSparkBlockManagerMemoryOffHeapUsed                                                                       MetricConfig `mapstructure:"databricks.spark.block_manager.memory.off_heap.used"`
	DatabricksSparkBlockManagerMemoryOnHeapMax                                                                         MetricConfig `mapstructure:"databricks.spark.block_manager.memory.on_heap.max"`
	DatabricksSparkBlockManagerMemoryOnHeapUsed                                                                        MetricConfig `mapstructure:"databricks.spark.block_manager.memory.on_heap.used"`
	DatabricksSparkBlockManagerMemoryRemaining                                                                         MetricConfig `mapstructure:"databricks.spark.block_manager.memory.remaining"`
	DatabricksSparkBlockManagerMemoryRemainingOffHeap                                                                  MetricConfig `mapstructure:"databricks.spark.block_manager.memory.remaining.off_heap"`
	DatabricksSparkBlockManagerMemoryRemainingOnHeap                                                                   MetricConfig `mapstructure:"databricks.spark.block_manager.memory.remaining.on_heap"`
	DatabricksSparkBlockManagerMemoryUsed                                                                              MetricConfig `mapstructure:"databricks.spark.block_manager.memory.used"`
	DatabricksSparkCodeGeneratorCompilationTime                                                                        MetricConfig `mapstructure:"databricks.spark.code_generator.compilation.time"`
	DatabricksSparkCodeGeneratorGeneratedClassSize                                                                     MetricConfig `mapstructure:"databricks.spark.code_generator.generated_class_size"`
	DatabricksSparkCodeGeneratorGeneratedMethodSize                                                                    MetricConfig `mapstructure:"databricks.spark.code_generator.generated_method_size"`
	DatabricksSparkCodeGeneratorSourcecodeSize                                                                         MetricConfig `mapstructure:"databricks.spark.code_generator.sourcecode_size"`
	DatabricksSparkDagSchedulerJobsActive                                                                              MetricConfig `mapstructure:"databricks.spark.dag_scheduler.jobs.active"`
	DatabricksSparkDagSchedulerJobsAll                                                                                 MetricConfig `mapstructure:"databricks.spark.dag_scheduler.jobs.all"`
	DatabricksSparkDagSchedulerStagesFailed                                                                            MetricConfig `mapstructure:"databricks.spark.dag_scheduler.stages.failed"`
	DatabricksSparkDagSchedulerStagesRunning                                                                           MetricConfig `mapstructure:"databricks.spark.dag_scheduler.stages.running"`
	DatabricksSparkDagSchedulerStagesWaiting                                                                           MetricConfig `mapstructure:"databricks.spark.dag_scheduler.stages.waiting"`
	DatabricksSparkDatabricksDirectoryCommitAutoVacuumCount                                                            MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.auto_vacuum.count"`
	DatabricksSparkDatabricksDirectoryCommitDeletedFilesFiltered                                                       MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.deleted_files_filtered"`
	DatabricksSparkDatabricksDirectoryCommitFilterListingCount                                                         MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.filter_listing.count"`
	DatabricksSparkDatabricksDirectoryCommitJobCommitCompleted                                                         MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.job_commit_completed"`
	DatabricksSparkDatabricksDirectoryCommitMarkerReadErrors                                                           MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.marker_read.errors"`
	DatabricksSparkDatabricksDirectoryCommitMarkerRefreshCount                                                         MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.marker_refresh.count"`
	DatabricksSparkDatabricksDirectoryCommitMarkerRefreshErrors                                                        MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.marker_refresh.errors"`
	DatabricksSparkDatabricksDirectoryCommitMarkersRead                                                                MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.markers.read"`
	DatabricksSparkDatabricksDirectoryCommitRepeatedListCount                                                          MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.repeated_list.count"`
	DatabricksSparkDatabricksDirectoryCommitUncommittedFilesFiltered                                                   MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.uncommitted_files.filtered"`
	DatabricksSparkDatabricksDirectoryCommitUntrackedFilesFound                                                        MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.untracked_files.found"`
	DatabricksSparkDatabricksDirectoryCommitVacuumCount                                                                MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.vacuum.count"`
	DatabricksSparkDatabricksDirectoryCommitVacuumErrors                                                               MetricConfig `mapstructure:"databricks.spark.databricks.directory_commit.vacuum.errors"`
	DatabricksSparkDatabricksPreemptionChecksCount                                                                     MetricConfig `mapstructure:"databricks.spark.databricks.preemption.checks.count"`
	DatabricksSparkDatabricksPreemptionPoolsAutoexpiredCount                                                           MetricConfig `mapstructure:"databricks.spark.databricks.preemption.pools_autoexpired.count"`
	DatabricksSparkDatabricksPreemptionPoolstarvationTime                                                              MetricConfig `mapstructure:"databricks.spark.databricks.preemption.poolstarvation.time"`
	DatabricksSparkDatabricksPreemptionSchedulerOverheadTime                                                           MetricConfig `mapstructure:"databricks.spark.databricks.preemption.scheduler_overhead.time"`
	DatabricksSparkDatabricksPreemptionTaskWastedTime                                                                  MetricConfig `mapstructure:"databricks.spark.databricks.preemption.task_wasted.time"`
	DatabricksSparkDatabricksPreemptionTasksPreemptedCount                                                             MetricConfig `mapstructure:"databricks.spark.databricks.preemption.tasks_preempted.count"`
	DatabricksSparkDatabricksTaskSchedulingLanesActivePools                                                            MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.active_pools"`
	DatabricksSparkDatabricksTaskSchedulingLanesBypassLaneActivePools                                                  MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.bypass_lane_active_pools"`
	DatabricksSparkDatabricksTaskSchedulingLanesFastLaneActivePools                                                    MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.fast_lane_active_pools"`
	DatabricksSparkDatabricksTaskSchedulingLanesFinishedQueriesTotalTaskTime                                           MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.finished_queries_total_task.time"`
	DatabricksSparkDatabricksTaskSchedulingLanesLaneCleanupMarkedPools                                                 MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.lane_cleanup.marked_pools"`
	DatabricksSparkDatabricksTaskSchedulingLanesLaneCleanupTwoPhasePoolsCleaned                                        MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.lane_cleanup.two_phase_pools_cleaned"`
	DatabricksSparkDatabricksTaskSchedulingLanesLaneCleanupZombiePoolsCleaned                                          MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.lane_cleanup.zombie_pools_cleaned"`
	DatabricksSparkDatabricksTaskSchedulingLanesPreemptionSlotTransferSuccessfulPreemptionIterationsCount              MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.preemption.slot_transfer_successful_preemption_iterations.count"`
	DatabricksSparkDatabricksTaskSchedulingLanesPreemptionSlotTransferTasksPreemptedCount                              MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.preemption.slot_transfer_tasks_preempted.count"`
	DatabricksSparkDatabricksTaskSchedulingLanesPreemptionSlotTransferWastedTaskTime                                   MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.preemption.slot_transfer_wasted_task.time"`
	DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationGradualDecreaseCount                                    MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.slot_reservation.gradual_decrease.count"`
	DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationQuickDropCount                                          MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.slot_reservation.quick_drop.count"`
	DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationQuickJumpCount                                          MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.slot_reservation.quick_jump.count"`
	DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationSlotsReserved                                           MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.slot_reservation.slots_reserved"`
	DatabricksSparkDatabricksTaskSchedulingLanesSlowLaneActivePools                                                    MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.slow_lane_active_pools"`
	DatabricksSparkDatabricksTaskSchedulingLanesTotalquerygroupsfinished                                               MetricConfig `mapstructure:"databricks.spark.databricks.task_scheduling_lanes.totalquerygroupsfinished"`
	DatabricksSparkExecutorDiskUsed                                                                                    MetricConfig `mapstructure:"databricks.spark.executor.disk_used"`
	DatabricksSparkExecutorMaxMemory                                                                                   MetricConfig `mapstructure:"databricks.spark.executor.max_memory"`
	DatabricksSparkExecutorMemoryUsed                                                                                  MetricConfig `mapstructure:"databricks.spark.executor.memory_used"`
	DatabricksSparkExecutorTotalInputBytes                                                                             MetricConfig `mapstructure:"databricks.spark.executor.total_input_bytes"`
	DatabricksSparkExecutorTotalShuffleRead                                                                            MetricConfig `mapstructure:"databricks.spark.executor.total_shuffle_read"`
	DatabricksSparkExecutorTotalShuffleWrite                                                                           MetricConfig `mapstructure:"databricks.spark.executor.total_shuffle_write"`
	DatabricksSparkExecutorMetricsDirectPoolMemory                                                                     MetricConfig `mapstructure:"databricks.spark.executor_metrics.direct_pool.memory"`
	DatabricksSparkExecutorMetricsJvmHeapMemory                                                                        MetricConfig `mapstructure:"databricks.spark.executor_metrics.jvm.heap.memory"`
	DatabricksSparkExecutorMetricsJvmOffHeapMemory                                                                     MetricConfig `mapstructure:"databricks.spark.executor_metrics.jvm.off_heap.memory"`
	DatabricksSparkExecutorMetricsMajorGcCount                                                                         MetricConfig `mapstructure:"databricks.spark.executor_metrics.major_gc.count"`
	DatabricksSparkExecutorMetricsMajorGcTime                                                                          MetricConfig `mapstructure:"databricks.spark.executor_metrics.major_gc.time"`
	DatabricksSparkExecutorMetricsMappedPoolMemory                                                                     MetricConfig `mapstructure:"databricks.spark.executor_metrics.mapped_pool.memory"`
	DatabricksSparkExecutorMetricsMinorGcCount                                                                         MetricConfig `mapstructure:"databricks.spark.executor_metrics.minor_gc.count"`
	DatabricksSparkExecutorMetricsMinorGcTime                                                                          MetricConfig `mapstructure:"databricks.spark.executor_metrics.minor_gc.time"`
	DatabricksSparkExecutorMetricsOffHeapExecutionMemory                                                               MetricConfig `mapstructure:"databricks.spark.executor_metrics.off_heap.execution.memory"`
	DatabricksSparkExecutorMetricsOffHeapStorageMemory                                                                 MetricConfig `mapstructure:"databricks.spark.executor_metrics.off_heap.storage.memory"`
	DatabricksSparkExecutorMetricsOffHeapUnifiedMemory                                                                 MetricConfig `mapstructure:"databricks.spark.executor_metrics.off_heap.unified.memory"`
	DatabricksSparkExecutorMetricsOnHeapExecutionMemory                                                                MetricConfig `mapstructure:"databricks.spark.executor_metrics.on_heap.execution.memory"`
	DatabricksSparkExecutorMetricsOnHeapStorageMemory                                                                  MetricConfig `mapstructure:"databricks.spark.executor_metrics.on_heap.storage.memory"`
	DatabricksSparkExecutorMetricsOnHeapUnifiedMemory                                                                  MetricConfig `mapstructure:"databricks.spark.executor_metrics.on_heap.unified.memory"`
	DatabricksSparkExecutorMetricsProcessTreeJvmRssMemory                                                              MetricConfig `mapstructure:"databricks.spark.executor_metrics.process_tree.jvm_rss.memory"`
	DatabricksSparkExecutorMetricsProcessTreeJvmVMemory                                                                MetricConfig `mapstructure:"databricks.spark.executor_metrics.process_tree.jvm_v.memory"`
	DatabricksSparkExecutorMetricsProcessTreeOtherRssMemory                                                            MetricConfig `mapstructure:"databricks.spark.executor_metrics.process_tree.other_rss.memory"`
	DatabricksSparkExecutorMetricsProcessTreeOtherVMemory                                                              MetricConfig `mapstructure:"databricks.spark.executor_metrics.process_tree.other_v.memory"`
	DatabricksSparkExecutorMetricsProcessTreePythonRssMemory                                                           MetricConfig `mapstructure:"databricks.spark.executor_metrics.process_tree.python_rss.memory"`
	DatabricksSparkExecutorMetricsProcessTreePythonVMemory                                                             MetricConfig `mapstructure:"databricks.spark.executor_metrics.process_tree.python_v.memory"`
	DatabricksSparkHiveExternalCatalogFileCacheHits                                                                    MetricConfig `mapstructure:"databricks.spark.hive_external_catalog.file_cache.hits"`
	DatabricksSparkHiveExternalCatalogFilesDiscovered                                                                  MetricConfig `mapstructure:"databricks.spark.hive_external_catalog.files_discovered"`
	DatabricksSparkHiveExternalCatalogHiveClientCalls                                                                  MetricConfig `mapstructure:"databricks.spark.hive_external_catalog.hive_client_calls"`
	DatabricksSparkHiveExternalCatalogParallelListingJobsCount                                                         MetricConfig `mapstructure:"databricks.spark.hive_external_catalog.parallel_listing_jobs.count"`
	DatabricksSparkHiveExternalCatalogPartitionsFetched                                                                MetricConfig `mapstructure:"databricks.spark.hive_external_catalog.partitions_fetched"`
	DatabricksSparkJobNumActiveStages                                                                                  MetricConfig `mapstructure:"databricks.spark.job.num_active_stages"`
	DatabricksSparkJobNumActiveTasks                                                                                   MetricConfig `mapstructure:"databricks.spark.job.num_active_tasks"`
	DatabricksSparkJobNumCompletedStages                                                                               MetricConfig `mapstructure:"databricks.spark.job.num_completed_stages"`
	DatabricksSparkJobNumCompletedTasks                                                                                MetricConfig `mapstructure:"databricks.spark.job.num_completed_tasks"`
	DatabricksSparkJobNumFailedStages                                                                                  MetricConfig `mapstructure:"databricks.spark.job.num_failed_stages"`
	DatabricksSparkJobNumFailedTasks                                                                                   MetricConfig `mapstructure:"databricks.spark.job.num_failed_tasks"`
	DatabricksSparkJobNumSkippedStages                                                                                 MetricConfig `mapstructure:"databricks.spark.job.num_skipped_stages"`
	DatabricksSparkJobNumSkippedTasks                                                                                  MetricConfig `mapstructure:"databricks.spark.job.num_skipped_tasks"`
	DatabricksSparkJobNumTasks                                                                                         MetricConfig `mapstructure:"databricks.spark.job.num_tasks"`
	DatabricksSparkJvmCPUTime                                                                                          MetricConfig `mapstructure:"databricks.spark.jvm.cpu.time"`
	DatabricksSparkLiveListenerBusEventsPostedCount                                                                    MetricConfig `mapstructure:"databricks.spark.live_listener_bus.events_posted.count"`
	DatabricksSparkLiveListenerBusQueueAppStatusDroppedEventsCount                                                     MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.app_status.dropped_events.count"`
	DatabricksSparkLiveListenerBusQueueAppstatusSize                                                                   MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.appstatus.size"`
	DatabricksSparkLiveListenerBusQueueExecutorManagementDroppedEventsCount                                            MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.executor_management.dropped_events.count"`
	DatabricksSparkLiveListenerBusQueueExecutormanagementSize                                                          MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.executormanagement.size"`
	DatabricksSparkLiveListenerBusQueueSharedDroppedEventsCount                                                        MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.shared.dropped_events.count"`
	DatabricksSparkLiveListenerBusQueueSharedSize                                                                      MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.shared.size"`
	DatabricksSparkLiveListenerBusQueueStreamsDroppedEventsCount                                                       MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.streams.dropped_events.count"`
	DatabricksSparkLiveListenerBusQueueStreamsSize                                                                     MetricConfig `mapstructure:"databricks.spark.live_listener_bus.queue.streams.size"`
	DatabricksSparkSparkSQLOperationManagerHiveOperationsCount                                                         MetricConfig `mapstructure:"databricks.spark.spark_sql_operation_manager.hive_operations.count"`
	DatabricksSparkStageDiskBytesSpilled                                                                               MetricConfig `mapstructure:"databricks.spark.stage.disk_bytes_spilled"`
	DatabricksSparkStageExecutorRunTime                                                                                MetricConfig `mapstructure:"databricks.spark.stage.executor_run_time"`
	DatabricksSparkStageInputBytes                                                                                     MetricConfig `mapstructure:"databricks.spark.stage.input_bytes"`
	DatabricksSparkStageInputRecords                                                                                   MetricConfig `mapstructure:"databricks.spark.stage.input_records"`
	DatabricksSparkStageMemoryBytesSpilled                                                                             MetricConfig `mapstructure:"databricks.spark.stage.memory_bytes_spilled"`
	DatabricksSparkStageOutputBytes                                                                                    MetricConfig `mapstructure:"databricks.spark.stage.output_bytes"`
	DatabricksSparkStageOutputRecords                                                                                  MetricConfig `mapstructure:"databricks.spark.stage.output_records"`
	DatabricksSparkTimerDagSchedulerMessageProcessingTime                                                              MetricConfig `mapstructure:"databricks.spark.timer.dag_scheduler.message_processing.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLExecutionStreamingQueryListenerBusTime          MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.sql.execution.streaming.query_listener_bus.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLExecutionTime                                   MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.sql.execution.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLExecutionUISQLAppStatusListenerTime             MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.sql.execution.ui.sql_app_status_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLHiveThriftserverUIHiveThriftServer2listenerTime MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.sql.hive.thriftserver.ui.hive_thrift_server2listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLSparkSessionTime                                MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.sql.spark_session.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLUtilExecutionListenerBusTime                    MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.sql.util.execution_listener_bus.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkStatusAppStatusListenerTime                        MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.status.app_status_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkUtilProfilerEnvTime                                MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.apache.spark.util.profiler_env.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksBackendDaemonDriverDataPlaneEventListenerTime       MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.backend.daemon.driver.data_plane_event_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksBackendDaemonDriverDbcEventLoggingListenerTime      MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.backend.daemon.driver.dbc_event_logging_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksPhotonPhotonCleanupListenerTime                     MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.photon.photon_cleanup_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSparkUtilExecutorTimeLoggingListenerTime            MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.spark.util.executor_time_logging_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSparkUtilUsageLoggingListenerTime                   MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.spark.util.usage_logging_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLAdviceAdvisorListenerTime                        MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.sql.advice.advisor_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLDebuggerQueryWatchdogListenerTime                MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.sql.debugger.query_watchdog_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLExecutionUIIoCacheListenerTime                   MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.sql.execution.ui.io_cache_listener.time"`
	DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLIoCachingRepeatedReadsEstimatorTime              MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.listener_processing.databricks.sql.io.caching.repeated_reads_estimator.time"`
	DatabricksSparkTimerLiveListenerBusQueueAppStatusListenerProcessingTime                                            MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.queue.app_status.listener_processing.time"`
	DatabricksSparkTimerLiveListenerBusQueueExecutorManagementListenerProcessingTime                                   MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.queue.executor_management.listener_processing.time"`
	DatabricksSparkTimerLiveListenerBusQueueSharedListenerProcessingTime                                               MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.queue.shared.listener_processing.time"`
	DatabricksSparkTimerLiveListenerBusQueueStreamsListenerProcessingTime                                              MetricConfig `mapstructure:"databricks.spark.timer.live_listener_bus.queue.streams.listener_processing.time"`
	DatabricksTasksRunDuration                                                                                         MetricConfig `mapstructure:"databricks.tasks.run.duration"`
	DatabricksTasksScheduleStatus                                                                                      MetricConfig `mapstructure:"databricks.tasks.schedule.status"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DatabricksJobsActiveTotal: MetricConfig{
			Enabled: true,
		},
		DatabricksJobsRunDuration: MetricConfig{
			Enabled: true,
		},
		DatabricksJobsScheduleStatus: MetricConfig{
			Enabled: true,
		},
		DatabricksJobsTotal: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryDiskSpaceUsed: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryMax: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryOffHeapMax: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryOffHeapUsed: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryOnHeapMax: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryOnHeapUsed: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryRemaining: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryRemainingOffHeap: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryRemainingOnHeap: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkBlockManagerMemoryUsed: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkCodeGeneratorCompilationTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkCodeGeneratorGeneratedClassSize: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkCodeGeneratorGeneratedMethodSize: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkCodeGeneratorSourcecodeSize: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDagSchedulerJobsActive: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDagSchedulerJobsAll: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDagSchedulerStagesFailed: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDagSchedulerStagesRunning: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDagSchedulerStagesWaiting: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitAutoVacuumCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitDeletedFilesFiltered: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitFilterListingCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitJobCommitCompleted: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitMarkerReadErrors: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitMarkerRefreshCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitMarkerRefreshErrors: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitMarkersRead: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitRepeatedListCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitUncommittedFilesFiltered: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitUntrackedFilesFound: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitVacuumCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksDirectoryCommitVacuumErrors: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksPreemptionChecksCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksPreemptionPoolsAutoexpiredCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksPreemptionPoolstarvationTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksPreemptionSchedulerOverheadTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksPreemptionTaskWastedTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksPreemptionTasksPreemptedCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesActivePools: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesBypassLaneActivePools: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesFastLaneActivePools: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesFinishedQueriesTotalTaskTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesLaneCleanupMarkedPools: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesLaneCleanupTwoPhasePoolsCleaned: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesLaneCleanupZombiePoolsCleaned: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesPreemptionSlotTransferSuccessfulPreemptionIterationsCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesPreemptionSlotTransferTasksPreemptedCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesPreemptionSlotTransferWastedTaskTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationGradualDecreaseCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationQuickDropCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationQuickJumpCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesSlotReservationSlotsReserved: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesSlowLaneActivePools: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkDatabricksTaskSchedulingLanesTotalquerygroupsfinished: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorDiskUsed: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMaxMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMemoryUsed: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorTotalInputBytes: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorTotalShuffleRead: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorTotalShuffleWrite: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsDirectPoolMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsJvmHeapMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsJvmOffHeapMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsMajorGcCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsMajorGcTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsMappedPoolMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsMinorGcCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsMinorGcTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsOffHeapExecutionMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsOffHeapStorageMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsOffHeapUnifiedMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsOnHeapExecutionMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsOnHeapStorageMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsOnHeapUnifiedMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsProcessTreeJvmRssMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsProcessTreeJvmVMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsProcessTreeOtherRssMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsProcessTreeOtherVMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsProcessTreePythonRssMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkExecutorMetricsProcessTreePythonVMemory: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkHiveExternalCatalogFileCacheHits: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkHiveExternalCatalogFilesDiscovered: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkHiveExternalCatalogHiveClientCalls: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkHiveExternalCatalogParallelListingJobsCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkHiveExternalCatalogPartitionsFetched: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumActiveStages: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumActiveTasks: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumCompletedStages: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumCompletedTasks: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumFailedStages: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumFailedTasks: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumSkippedStages: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumSkippedTasks: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJobNumTasks: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkJvmCPUTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusEventsPostedCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueAppStatusDroppedEventsCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueAppstatusSize: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueExecutorManagementDroppedEventsCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueExecutormanagementSize: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueSharedDroppedEventsCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueSharedSize: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueStreamsDroppedEventsCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkLiveListenerBusQueueStreamsSize: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkSparkSQLOperationManagerHiveOperationsCount: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkStageDiskBytesSpilled: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkStageExecutorRunTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkStageInputBytes: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkStageInputRecords: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkStageMemoryBytesSpilled: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkStageOutputBytes: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkStageOutputRecords: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerDagSchedulerMessageProcessingTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLExecutionStreamingQueryListenerBusTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLExecutionTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLExecutionUISQLAppStatusListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLHiveThriftserverUIHiveThriftServer2listenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLSparkSessionTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkSQLUtilExecutionListenerBusTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkStatusAppStatusListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingApacheSparkUtilProfilerEnvTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksBackendDaemonDriverDataPlaneEventListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksBackendDaemonDriverDbcEventLoggingListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksPhotonPhotonCleanupListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSparkUtilExecutorTimeLoggingListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSparkUtilUsageLoggingListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLAdviceAdvisorListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLDebuggerQueryWatchdogListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLExecutionUIIoCacheListenerTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusListenerProcessingDatabricksSQLIoCachingRepeatedReadsEstimatorTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusQueueAppStatusListenerProcessingTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusQueueExecutorManagementListenerProcessingTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusQueueSharedListenerProcessingTime: MetricConfig{
			Enabled: true,
		},
		DatabricksSparkTimerLiveListenerBusQueueStreamsListenerProcessingTime: MetricConfig{
			Enabled: true,
		},
		DatabricksTasksRunDuration: MetricConfig{
			Enabled: true,
		},
		DatabricksTasksScheduleStatus: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// ResourceAttributesConfig provides config for databricks resource attributes.
type ResourceAttributesConfig struct {
	DatabricksInstanceName ResourceAttributeConfig `mapstructure:"databricks.instance.name"`
	SparkAppID             ResourceAttributeConfig `mapstructure:"spark.app.id"`
	SparkClusterID         ResourceAttributeConfig `mapstructure:"spark.cluster.id"`
	SparkClusterName       ResourceAttributeConfig `mapstructure:"spark.cluster.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		DatabricksInstanceName: ResourceAttributeConfig{
			Enabled: true,
		},
		SparkAppID: ResourceAttributeConfig{
			Enabled: true,
		},
		SparkClusterID: ResourceAttributeConfig{
			Enabled: true,
		},
		SparkClusterName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for databricks metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
