// Code generated by monitor-code-gen. DO NOT EDIT.

package diskio

import (
	"github.com/signalfx/golib/v3/datapoint" //nolint:staticcheck // SA1019: deprecated package still in use

	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "disk-io"

var groupSet = map[string]bool{}

const (
	diskMergedRead  = "disk_merged.read"
	diskMergedWrite = "disk_merged.write"
	diskOctetsRead  = "disk_octets.read"
	diskOctetsWrite = "disk_octets.write"
	diskOpsPending  = "disk_ops.pending"
	diskOpsRead     = "disk_ops.read"
	diskOpsTotal    = "disk_ops.total"
	diskOpsWrite    = "disk_ops.write"
	diskTimeRead    = "disk_time.read"
	diskTimeWrite   = "disk_time.write"
)

var metricSet = map[string]monitors.MetricInfo{
	diskMergedRead:  {Type: datapoint.Counter},
	diskMergedWrite: {Type: datapoint.Counter},
	diskOctetsRead:  {Type: datapoint.Counter},
	diskOctetsWrite: {Type: datapoint.Counter},
	diskOpsPending:  {Type: datapoint.Gauge},
	diskOpsRead:     {Type: datapoint.Counter},
	diskOpsTotal:    {Type: datapoint.Gauge},
	diskOpsWrite:    {Type: datapoint.Counter},
	diskTimeRead:    {Type: datapoint.Counter},
	diskTimeWrite:   {Type: datapoint.Counter},
}

var defaultMetrics = map[string]bool{
	diskOpsRead:  true,
	diskOpsTotal: true,
	diskOpsWrite: true,
}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "disk-io",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
