// Code generated by monitor-code-gen. DO NOT EDIT.

package windowslegacy

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "windows-legacy"

var groupSet = map[string]bool{}

const (
	logicaldiskDiskReadBytesSec              = "logicaldisk.disk_read_bytes_sec"
	logicaldiskDiskReadsSec                  = "logicaldisk.disk_reads_sec"
	logicaldiskDiskTransfersSec              = "logicaldisk.disk_transfers_sec"
	logicaldiskDiskWriteBytesSec             = "logicaldisk.disk_write_bytes_sec"
	logicaldiskDiskWritesSec                 = "logicaldisk.disk_writes_sec"
	logicaldiskFreeMegabytes                 = "logicaldisk.free_megabytes"
	logicaldiskPctFreeSpace                  = "logicaldisk.pct_free_space"
	memoryAvailableMbytes                    = "memory.available_mbytes"
	memoryPagesInputSec                      = "memory.pages_input_sec"
	networkInterfaceBytesReceivedSec         = "network_interface.bytes_received_sec"
	networkInterfaceBytesSentSec             = "network_interface.bytes_sent_sec"
	networkInterfaceBytesTotalSec            = "network_interface.bytes_total_sec"
	networkInterfaceCurrentBandwidth         = "network_interface.current_bandwidth"
	networkInterfacePacketsOutboundDiscarded = "network_interface.packets_outbound_discarded"
	networkInterfacePacketsOutboundErrors    = "network_interface.packets_outbound_errors"
	networkInterfacePacketsReceivedDiscarded = "network_interface.packets_received_discarded"
	networkInterfacePacketsReceivedErrors    = "network_interface.packets_received_errors"
	networkInterfacePacketsReceivedSec       = "network_interface.packets_received_sec"
	networkInterfacePacketsSentSec           = "network_interface.packets_sent_sec"
	pagingFilePctUsage                       = "paging_file.pct_usage"
	pagingFilePctUsagePeak                   = "paging_file.pct_usage_peak"
	physicaldiskAvgDiskSecRead               = "physicaldisk.avg_disk_sec_read"
	physicaldiskAvgDiskSecTransfer           = "physicaldisk.avg_disk_sec_transfer"
	physicaldiskAvgDiskSecWrite              = "physicaldisk.avg_disk_sec_write"
	processorInterruptsSec                   = "processor.interrupts_sec"
	processorPctPrivilegedTime               = "processor.pct_privileged_time"
	processorPctProcessorTime                = "processor.pct_processor_time"
	processorPctUserTime                     = "processor.pct_user_time"
	systemContextSwitchesSec                 = "system.context_switches_sec"
	systemProcessorQueueLength               = "system.processor_queue_length"
	systemSystemCallsSec                     = "system.system_calls_sec"
)

var metricSet = map[string]monitors.MetricInfo{
	logicaldiskDiskReadBytesSec:              {Type: datapoint.Gauge},
	logicaldiskDiskReadsSec:                  {Type: datapoint.Gauge},
	logicaldiskDiskTransfersSec:              {Type: datapoint.Gauge},
	logicaldiskDiskWriteBytesSec:             {Type: datapoint.Gauge},
	logicaldiskDiskWritesSec:                 {Type: datapoint.Gauge},
	logicaldiskFreeMegabytes:                 {Type: datapoint.Gauge},
	logicaldiskPctFreeSpace:                  {Type: datapoint.Gauge},
	memoryAvailableMbytes:                    {Type: datapoint.Gauge},
	memoryPagesInputSec:                      {Type: datapoint.Gauge},
	networkInterfaceBytesReceivedSec:         {Type: datapoint.Gauge},
	networkInterfaceBytesSentSec:             {Type: datapoint.Gauge},
	networkInterfaceBytesTotalSec:            {Type: datapoint.Gauge},
	networkInterfaceCurrentBandwidth:         {Type: datapoint.Gauge},
	networkInterfacePacketsOutboundDiscarded: {Type: datapoint.Gauge},
	networkInterfacePacketsOutboundErrors:    {Type: datapoint.Gauge},
	networkInterfacePacketsReceivedDiscarded: {Type: datapoint.Gauge},
	networkInterfacePacketsReceivedErrors:    {Type: datapoint.Gauge},
	networkInterfacePacketsReceivedSec:       {Type: datapoint.Gauge},
	networkInterfacePacketsSentSec:           {Type: datapoint.Gauge},
	pagingFilePctUsage:                       {Type: datapoint.Gauge},
	pagingFilePctUsagePeak:                   {Type: datapoint.Gauge},
	physicaldiskAvgDiskSecRead:               {Type: datapoint.Gauge},
	physicaldiskAvgDiskSecTransfer:           {Type: datapoint.Gauge},
	physicaldiskAvgDiskSecWrite:              {Type: datapoint.Gauge},
	processorInterruptsSec:                   {Type: datapoint.Gauge},
	processorPctPrivilegedTime:               {Type: datapoint.Gauge},
	processorPctProcessorTime:                {Type: datapoint.Gauge},
	processorPctUserTime:                     {Type: datapoint.Gauge},
	systemContextSwitchesSec:                 {Type: datapoint.Gauge},
	systemProcessorQueueLength:               {Type: datapoint.Gauge},
	systemSystemCallsSec:                     {Type: datapoint.Gauge},
}

var defaultMetrics = map[string]bool{
	logicaldiskDiskReadsSec:               true,
	logicaldiskDiskWritesSec:              true,
	logicaldiskFreeMegabytes:              true,
	logicaldiskPctFreeSpace:               true,
	memoryAvailableMbytes:                 true,
	memoryPagesInputSec:                   true,
	networkInterfaceBytesReceivedSec:      true,
	networkInterfaceBytesSentSec:          true,
	networkInterfaceBytesTotalSec:         true,
	networkInterfacePacketsOutboundErrors: true,
	networkInterfacePacketsReceivedErrors: true,
	pagingFilePctUsage:                    true,
	processorPctProcessorTime:             true,
}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "windows-legacy",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
