#!/bin/sh
# Checks TLS behavior against IP-literal targets end to end by running the
# full example Docker Compose stack with a locally built package. There are
# two independent gaps involved:
#
#  1. On every startup, the modular input calls back into Splunk's own
#     management API at the literal https://127.0.0.1:8089 (see
#     internal/auth/auth.go), which must succeed against Splunk's
#     self-signed default certificate for the input to ever listen. The
#     wait loop below catches a regression here directly: if this call
#     fails, the OTLP ports never open.
#  2. Separately, the server certificate generated by generate-certs.sh for
#     the receiver's own TLS listener must carry an IP SAN, not just DNS
#     SANs ("splunk", "localhost"), so a TLS client dialing the receiver by
#     IP address succeeds the same way a client dialing it by hostname
#     does. The checks after the wait loop cover that.
#
# Usage: OTLP_PACKAGE_PATH=/path/to/splunk-connect-for-otlp.tgz sh test-ip-sans.sh
#
# Required environment variables:
#   OTLP_PACKAGE_PATH  Path to a locally built splunk-connect-for-otlp.tgz

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

: "${OTLP_PACKAGE_PATH:?OTLP_PACKAGE_PATH must point to a locally built splunk-connect-for-otlp.tgz}"
OTLP_PACKAGE_PATH="$(cd "$(dirname "$OTLP_PACKAGE_PATH")" && pwd)/$(basename "$OTLP_PACKAGE_PATH")"

COMPOSE="docker compose -f docker-compose.yml -f docker-compose.test.yml --profile splunk"
HTTP_PORT=4318
WORKDIR="$(mktemp -d)"
CA_CRT="$WORKDIR/ca.crt"

cleanup() {
    status=$?
    if [ "$status" -ne 0 ]; then
        echo "==> Failure detected, dumping container logs"
        $COMPOSE logs splunk otelcollector cert-init || true
    fi
    echo "==> Tearing down Docker Compose stack"
    $COMPOSE down -v || true
    rm -rf "$WORKDIR"
    exit "$status"
}
trap cleanup EXIT

echo "==> Extracting locally built package: $OTLP_PACKAGE_PATH"
mkdir -p "$WORKDIR/package"
tar -xzf "$OTLP_PACKAGE_PATH" -C "$WORKDIR/package"
export OTLP_PACKAGE_DIR="$WORKDIR/package/splunk-connect-for-otlp"
mkdir -p "$OTLP_PACKAGE_DIR/local"
cp splunk-inputs-local.conf "$OTLP_PACKAGE_DIR/local/inputs.conf"

echo "==> Starting Docker Compose stack with locally built package"
$COMPOSE up -d

echo "==> Waiting for the OTLP HTTP port to accept connections"
timeout=240
elapsed=0
while ! curl -sk --max-time 2 -o /dev/null "https://localhost:${HTTP_PORT}/"; do
    if [ "$elapsed" -ge "$timeout" ]; then
        echo "Timeout: OTLP HTTP port ${HTTP_PORT} was not reachable within ${timeout}s"
        echo "The modular input calls back into Splunk's own management API"
        echo "at https://127.0.0.1:8089 on startup (see internal/auth/auth.go)."
        echo "If that call fails TLS verification against Splunk's own"
        echo "self-signed certificate, the input exits before ever listening."
        exit 1
    fi
    sleep 3
    elapsed=$((elapsed + 3))
done

echo "==> Extracting CA certificate from the splunk container"
$COMPOSE cp splunk:/certs/ca.crt "$CA_CRT"

assert_tls_ok() {
    host="$1"
    if curl -sS --max-time 10 --cacert "$CA_CRT" -o /dev/null "https://${host}:${HTTP_PORT}/v1/logs"; then
        echo "OK: TLS verification succeeded connecting to https://${host}:${HTTP_PORT}"
    else
        echo "FAIL: TLS verification failed connecting to https://${host}:${HTTP_PORT}"
        return 1
    fi
}

echo "==> Checking TLS verification via hostname (control case)"
assert_tls_ok localhost

echo "==> Checking TLS verification via IP literal"
if ! assert_tls_ok 127.0.0.1; then
    echo "The server certificate must carry an IP SAN so that a client"
    echo "dialing it by IP address succeeds, the same way a client dialing"
    echo "it by hostname does."
    exit 1
fi

echo "==> All TLS checks passed"
