// Copyright Splunk, Inc.
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package defaults

import (
	"github.com/signalfx/splunk-otel-collector/pkg/components"

	"github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector"
	"github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector"
	"github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector"
	"github.com/open-telemetry/opentelemetry-collector-contrib/connector/sumconnector"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudstorageexporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/ackextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/dbauth/awsiamdbauthextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/googlecloudlogentryencodingextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/textencodingextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/httpforwarderextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/k8sleaderelector"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/dockerobserver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/ecsobserver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/hostobserver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/k8sobserver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricsgenerationprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/activedirectorydsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/apachereceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/apachesparkreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscloudwatchreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureblobreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureeventhubreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azuremonitorreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/carbonreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/chronyreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ciscoosreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/cloudfoundryreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dnscheckreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filestatsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/haproxyreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/icmpcheckreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/iisreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/influxdbreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkametricsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/memcachedreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ntpreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/oracledbreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/purefareceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/saphanareceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/snmpreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/snowflakereceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/solacereceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkenterprisereceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sshcheckreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/systemdreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcpcheckreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tlscheckreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/udplogreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/wavefrontreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowseventlogreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsservicereceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/yanggrpcreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver"
	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zookeeperreceiver"
	"go.opentelemetry.io/collector/connector/forwardconnector"
	"go.opentelemetry.io/collector/exporter/debugexporter"
	"go.opentelemetry.io/collector/exporter/nopexporter"
	"go.opentelemetry.io/collector/exporter/otlpexporter"
	"go.opentelemetry.io/collector/exporter/otlphttpexporter"
	"go.opentelemetry.io/collector/extension/zpagesextension"
	"go.opentelemetry.io/collector/processor/batchprocessor"
	"go.opentelemetry.io/collector/processor/memorylimiterprocessor"
	"go.opentelemetry.io/collector/receiver/nopreceiver"
	"go.opentelemetry.io/collector/receiver/otlpreceiver"

	"github.com/signalfx/splunk-otel-collector/internal/extension/configsourcetelemetryextension"
	"github.com/signalfx/splunk-otel-collector/internal/receiver/discoveryreceiver"
	"github.com/signalfx/splunk-otel-collector/internal/receiver/gnmireceiver"
	"github.com/signalfx/splunk-otel-collector/internal/receiver/lightprometheusreceiver"
	"github.com/signalfx/splunk-otel-collector/internal/receiver/scriptedinputsreceiver"
	"github.com/signalfx/splunk-otel-collector/internal/receiver/signalfxgatewayprometheusremotewritereceiver"
	"github.com/signalfx/splunk-otel-collector/pkg/extension/smartagentextension"
	"github.com/signalfx/splunk-otel-collector/pkg/processor/rollingspanlatencyprocessor"
	"github.com/signalfx/splunk-otel-collector/pkg/processor/timestampprocessor"
	"github.com/signalfx/splunk-otel-collector/pkg/receiver/smartagentreceiver"
)

// RegisterDefaults registers every component that ships with this collector distribution
// into r's Extensions, Receivers, Processors, Exporters, and Connectors registries. Callers
// assembling a customized distribution typically call components.NewRegistries, then
// RegisterDefaults, then Register or Deregister their own factories on the result before
// calling Build.
func RegisterDefaults(r *components.Registries) {
	r.Extensions.Register(ackextension.NewFactory())
	r.Extensions.Register(awsiamdbauthextension.NewFactory())
	r.Extensions.Register(basicauthextension.NewFactory())
	r.Extensions.Register(bearertokenauthextension.NewFactory())
	r.Extensions.Register(configsourcetelemetryextension.NewFactory())
	r.Extensions.Register(dockerobserver.NewFactory())
	r.Extensions.Register(ecsobserver.NewFactory())
	r.Extensions.Register(filestorage.NewFactory())
	r.Extensions.Register(googlecloudlogentryencodingextension.NewFactory())
	r.Extensions.Register(headerssetterextension.NewFactory())
	r.Extensions.Register(healthcheckextension.NewFactory())
	r.Extensions.Register(hostobserver.NewFactory())
	r.Extensions.Register(httpforwarderextension.NewFactory())
	r.Extensions.Register(k8sleaderelector.NewFactory())
	r.Extensions.Register(k8sobserver.NewFactory())
	r.Extensions.Register(oauth2clientauthextension.NewFactory())
	r.Extensions.Register(opampextension.NewFactory())
	r.Extensions.Register(pprofextension.NewFactory())
	r.Extensions.Register(smartagentextension.NewFactory())
	r.Extensions.Register(textencodingextension.NewFactory())
	r.Extensions.Register(zpagesextension.NewFactory())

	r.Receivers.Register(activedirectorydsreceiver.NewFactory())
	r.Receivers.Register(apachereceiver.NewFactory())
	r.Receivers.Register(apachesparkreceiver.NewFactory())
	r.Receivers.Register(awscloudwatchreceiver.NewFactory())
	r.Receivers.Register(awscontainerinsightreceiver.NewFactory())
	r.Receivers.Register(awsecscontainermetricsreceiver.NewFactory())
	r.Receivers.Register(azureblobreceiver.NewFactory())
	r.Receivers.Register(azureeventhubreceiver.NewFactory())
	r.Receivers.Register(azuremonitorreceiver.NewFactory())
	r.Receivers.Register(carbonreceiver.NewFactory())
	r.Receivers.Register(chronyreceiver.NewFactory())
	r.Receivers.Register(ciscoosreceiver.NewFactory())
	r.Receivers.Register(cloudfoundryreceiver.NewFactory())
	r.Receivers.Register(collectdreceiver.NewFactory())
	r.Receivers.Register(discoveryreceiver.NewFactory())
	r.Receivers.Register(dnscheckreceiver.NewFactory())
	r.Receivers.Register(dockerstatsreceiver.NewFactory())
	r.Receivers.Register(elasticsearchreceiver.NewFactory())
	r.Receivers.Register(filelogreceiver.NewFactory())
	r.Receivers.Register(filestatsreceiver.NewFactory())
	r.Receivers.Register(fluentforwardreceiver.NewFactory())
	r.Receivers.Register(gnmireceiver.NewFactory())
	r.Receivers.Register(googlecloudpubsubreceiver.NewFactory())
	r.Receivers.Register(haproxyreceiver.NewFactory())
	r.Receivers.Register(hostmetricsreceiver.NewFactory())
	r.Receivers.Register(httpcheckreceiver.NewFactory())
	r.Receivers.Register(icmpcheckreceiver.NewFactory())
	r.Receivers.Register(iisreceiver.NewFactory())
	r.Receivers.Register(influxdbreceiver.NewFactory())
	r.Receivers.Register(jaegerreceiver.NewFactory())
	r.Receivers.Register(journaldreceiver.NewFactory())
	r.Receivers.Register(k8sclusterreceiver.NewFactory())
	r.Receivers.Register(k8seventsreceiver.NewFactory())
	r.Receivers.Register(k8sobjectsreceiver.NewFactory())
	r.Receivers.Register(kafkametricsreceiver.NewFactory())
	r.Receivers.Register(kafkareceiver.NewFactory())
	r.Receivers.Register(kubeletstatsreceiver.NewFactory())
	r.Receivers.Register(lightprometheusreceiver.NewFactory())
	r.Receivers.Register(memcachedreceiver.NewFactory())
	r.Receivers.Register(mongodbatlasreceiver.NewFactory())
	r.Receivers.Register(mongodbreceiver.NewFactory())
	r.Receivers.Register(mysqlreceiver.NewFactory())
	r.Receivers.Register(nginxreceiver.NewFactory())
	r.Receivers.Register(nopreceiver.NewFactory())
	r.Receivers.Register(ntpreceiver.NewFactory())
	r.Receivers.Register(oracledbreceiver.NewFactory())
	r.Receivers.Register(otlpreceiver.NewFactory())
	r.Receivers.Register(postgresqlreceiver.NewFactory())
	r.Receivers.Register(prometheusreceiver.NewFactory())
	r.Receivers.Register(prometheusremotewritereceiver.NewFactory())
	r.Receivers.Register(purefareceiver.NewFactory())
	r.Receivers.Register(rabbitmqreceiver.NewFactory())
	r.Receivers.Register(receivercreator.NewFactory())
	r.Receivers.Register(redisreceiver.NewFactory())
	r.Receivers.Register(saphanareceiver.NewFactory())
	r.Receivers.Register(scriptedinputsreceiver.NewFactory())
	r.Receivers.Register(signalfxgatewayprometheusremotewritereceiver.NewFactory())
	r.Receivers.Register(simpleprometheusreceiver.NewFactory())
	r.Receivers.Register(smartagentreceiver.NewFactory())
	r.Receivers.Register(snmpreceiver.NewFactory())
	r.Receivers.Register(snowflakereceiver.NewFactory())
	r.Receivers.Register(solacereceiver.NewFactory())
	r.Receivers.Register(splunkenterprisereceiver.NewFactory())
	r.Receivers.Register(splunkhecreceiver.NewFactory())
	r.Receivers.Register(sqlqueryreceiver.NewFactory())
	r.Receivers.Register(sqlserverreceiver.NewFactory())
	r.Receivers.Register(sshcheckreceiver.NewFactory())
	r.Receivers.Register(statsdreceiver.NewFactory())
	r.Receivers.Register(syslogreceiver.NewFactory())
	r.Receivers.Register(systemdreceiver.NewFactory())
	r.Receivers.Register(tcpcheckreceiver.NewFactory())
	r.Receivers.Register(tcplogreceiver.NewFactory())
	r.Receivers.Register(tlscheckreceiver.NewFactory())
	r.Receivers.Register(udplogreceiver.NewFactory())
	r.Receivers.Register(vcenterreceiver.NewFactory())
	r.Receivers.Register(wavefrontreceiver.NewFactory())
	r.Receivers.Register(windowseventlogreceiver.NewFactory())
	r.Receivers.Register(windowsperfcountersreceiver.NewFactory())
	r.Receivers.Register(windowsservicereceiver.NewFactory())
	r.Receivers.Register(yanggrpcreceiver.NewFactory())
	r.Receivers.Register(zipkinreceiver.NewFactory())
	r.Receivers.Register(zookeeperreceiver.NewFactory())

	r.Exporters.Register(awss3exporter.NewFactory())
	r.Exporters.Register(debugexporter.NewFactory())
	r.Exporters.Register(fileexporter.NewFactory())
	r.Exporters.Register(googlecloudstorageexporter.NewFactory())
	r.Exporters.Register(kafkaexporter.NewFactory())
	r.Exporters.Register(loadbalancingexporter.NewFactory())
	r.Exporters.Register(nopexporter.NewFactory())
	r.Exporters.Register(otlpexporter.NewFactory())
	r.Exporters.Register(otlphttpexporter.NewFactory())
	r.Exporters.Register(prometheusremotewriteexporter.NewFactory())
	r.Exporters.Register(signalfxexporter.NewFactory())
	r.Exporters.Register(splunkhecexporter.NewFactory())

	r.Processors.Register(attributesprocessor.NewFactory())
	r.Processors.Register(batchprocessor.NewFactory())
	r.Processors.Register(cumulativetodeltaprocessor.NewFactory())
	r.Processors.Register(filterprocessor.NewFactory())
	r.Processors.Register(groupbyattrsprocessor.NewFactory())
	r.Processors.Register(k8sattributesprocessor.NewFactory())
	r.Processors.Register(logstransformprocessor.NewFactory())
	r.Processors.Register(memorylimiterprocessor.NewFactory())
	r.Processors.Register(metricsgenerationprocessor.NewFactory())
	r.Processors.Register(metricstransformprocessor.NewFactory())
	r.Processors.Register(probabilisticsamplerprocessor.NewFactory())
	r.Processors.Register(redactionprocessor.NewFactory())
	r.Processors.Register(resourcedetectionprocessor.NewFactory())
	r.Processors.Register(resourceprocessor.NewFactory())
	r.Processors.Register(spanprocessor.NewFactory())
	r.Processors.Register(tailsamplingprocessor.NewFactory())
	r.Processors.Register(timestampprocessor.NewFactory())
	r.Processors.Register(rollingspanlatencyprocessor.NewFactory())
	r.Processors.Register(transformprocessor.NewFactory())

	r.Connectors.Register(countconnector.NewFactory())
	r.Connectors.Register(forwardconnector.NewFactory())
	r.Connectors.Register(routingconnector.NewFactory())
	r.Connectors.Register(spanmetricsconnector.NewFactory())
	r.Connectors.Register(sumconnector.NewFactory())
}
