// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"slices"
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

var MetricsInfo = metricsInfo{
	PtpClockState: metricInfo{
		Name:       "ptp.clock.state",
		Attributes: []string{"ptp.clock.state"},
	},
	PtpGrandmasterInfo: metricInfo{
		Name:       "ptp.grandmaster.info",
		Attributes: []string{"ptp.grandmaster.identity"},
	},
	PtpGrandmasterPresent: metricInfo{
		Name: "ptp.grandmaster.present",
	},
	PtpOffset: metricInfo{
		Name: "ptp.offset",
	},
	PtpPathDelay: metricInfo{
		Name: "ptp.path.delay",
	},
	PtpPortState: metricInfo{
		Name:       "ptp.port.state",
		Attributes: []string{"ptp.port.identity", "ptp.port.state"},
	},
}

type metricsInfo struct {
	PtpClockState         metricInfo
	PtpGrandmasterInfo    metricInfo
	PtpGrandmasterPresent metricInfo
	PtpOffset             metricInfo
	PtpPathDelay          metricInfo
	PtpPortState          metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricPtpClockState struct {
	data          pmetric.Metric            // data buffer for generated metric.
	config        PtpClockStateMetricConfig // metric config provided by user.
	capacity      int                       // max observed number of data points added to the metric.
	aggDataPoints []int64                   // slice containing number of aggregated datapoints at each index
}

// init fills ptp.clock.state metric with initial data.
func (m *metricPtpClockState) init() {
	m.data.SetName("ptp.clock.state")
	m.data.SetDescription("Local PTP clock state inferred from the states of its ports (1 for the reported state).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricPtpClockState) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, ptpClockStateAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, PtpClockStateMetricAttributeKeyPtpClockState) {
		dp.Attributes().PutStr("ptp.clock.state", ptpClockStateAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPtpClockState) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPtpClockState) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPtpClockState(cfg PtpClockStateMetricConfig) metricPtpClockState {
	m := metricPtpClockState{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPtpGrandmasterInfo struct {
	data          pmetric.Metric                 // data buffer for generated metric.
	config        PtpGrandmasterInfoMetricConfig // metric config provided by user.
	capacity      int                            // max observed number of data points added to the metric.
	aggDataPoints []int64                        // slice containing number of aggregated datapoints at each index
}

// init fills ptp.grandmaster.info metric with initial data.
func (m *metricPtpGrandmasterInfo) init() {
	m.data.SetName("ptp.grandmaster.info")
	m.data.SetDescription("Selected remote PTP grandmaster identity (1 for the selected identity). Omitted when ptp4l reports no remote grandmaster.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricPtpGrandmasterInfo) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, ptpGrandmasterIdentityAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, PtpGrandmasterInfoMetricAttributeKeyPtpGrandmasterIdentity) {
		dp.Attributes().PutStr("ptp.grandmaster.identity", ptpGrandmasterIdentityAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPtpGrandmasterInfo) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPtpGrandmasterInfo) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPtpGrandmasterInfo(cfg PtpGrandmasterInfoMetricConfig) metricPtpGrandmasterInfo {
	m := metricPtpGrandmasterInfo{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPtpGrandmasterPresent struct {
	data     pmetric.Metric                    // data buffer for generated metric.
	config   PtpGrandmasterPresentMetricConfig // metric config provided by user.
	capacity int                               // max observed number of data points added to the metric.
}

// init fills ptp.grandmaster.present metric with initial data.
func (m *metricPtpGrandmasterPresent) init() {
	m.data.SetName("ptp.grandmaster.present")
	m.data.SetDescription("Whether ptp4l reports a remote grandmaster (1 for present, 0 when the local clock is reported as grandmaster).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
}

func (m *metricPtpGrandmasterPresent) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPtpGrandmasterPresent) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPtpGrandmasterPresent) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPtpGrandmasterPresent(cfg PtpGrandmasterPresentMetricConfig) metricPtpGrandmasterPresent {
	m := metricPtpGrandmasterPresent{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPtpOffset struct {
	data     pmetric.Metric        // data buffer for generated metric.
	config   PtpOffsetMetricConfig // metric config provided by user.
	capacity int                   // max observed number of data points added to the metric.
}

// init fills ptp.offset metric with initial data.
func (m *metricPtpOffset) init() {
	m.data.SetName("ptp.offset")
	m.data.SetDescription("Signed offset of the local PTP clock from a remote grandmaster, reported in seconds. Omitted when ptp4l reports no remote grandmaster.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
}

func (m *metricPtpOffset) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPtpOffset) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPtpOffset) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPtpOffset(cfg PtpOffsetMetricConfig) metricPtpOffset {
	m := metricPtpOffset{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPtpPathDelay struct {
	data     pmetric.Metric           // data buffer for generated metric.
	config   PtpPathDelayMetricConfig // metric config provided by user.
	capacity int                      // max observed number of data points added to the metric.
}

// init fills ptp.path.delay metric with initial data.
func (m *metricPtpPathDelay) init() {
	m.data.SetName("ptp.path.delay")
	m.data.SetDescription("Mean path delay to a remote PTP grandmaster, reported in seconds. Omitted when ptp4l reports no remote grandmaster.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
}

func (m *metricPtpPathDelay) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPtpPathDelay) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPtpPathDelay) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPtpPathDelay(cfg PtpPathDelayMetricConfig) metricPtpPathDelay {
	m := metricPtpPathDelay{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPtpPortState struct {
	data          pmetric.Metric           // data buffer for generated metric.
	config        PtpPortStateMetricConfig // metric config provided by user.
	capacity      int                      // max observed number of data points added to the metric.
	aggDataPoints []int64                  // slice containing number of aggregated datapoints at each index
}

// init fills ptp.port.state metric with initial data.
func (m *metricPtpPortState) init() {
	m.data.SetName("ptp.port.state")
	m.data.SetDescription("State of each local PTP port (1 for the reported state).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricPtpPortState) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, ptpPortIdentityAttributeValue string, ptpPortStateAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, PtpPortStateMetricAttributeKeyPtpPortIdentity) {
		dp.Attributes().PutStr("ptp.port.identity", ptpPortIdentityAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, PtpPortStateMetricAttributeKeyPtpPortState) {
		dp.Attributes().PutStr("ptp.port.state", ptpPortStateAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPtpPortState) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPtpPortState) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPtpPortState(cfg PtpPortStateMetricConfig) metricPtpPortState {
	m := metricPtpPortState{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricPtpClockState            metricPtpClockState
	metricPtpGrandmasterInfo       metricPtpGrandmasterInfo
	metricPtpGrandmasterPresent    metricPtpGrandmasterPresent
	metricPtpOffset                metricPtpOffset
	metricPtpPathDelay             metricPtpPathDelay
	metricPtpPortState             metricPtpPortState
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricPtpClockState:            newMetricPtpClockState(mbc.Metrics.PtpClockState),
		metricPtpGrandmasterInfo:       newMetricPtpGrandmasterInfo(mbc.Metrics.PtpGrandmasterInfo),
		metricPtpGrandmasterPresent:    newMetricPtpGrandmasterPresent(mbc.Metrics.PtpGrandmasterPresent),
		metricPtpOffset:                newMetricPtpOffset(mbc.Metrics.PtpOffset),
		metricPtpPathDelay:             newMetricPtpPathDelay(mbc.Metrics.PtpPathDelay),
		metricPtpPortState:             newMetricPtpPortState(mbc.Metrics.PtpPortState),
		resourceAttributeIncludeFilter: make(map[string]filter.Filter),
		resourceAttributeExcludeFilter: make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.PtpClockType.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ptp.clock.type"] = filter.CreateFilter(mbc.ResourceAttributes.PtpClockType.MetricsInclude)
	}
	if mbc.ResourceAttributes.PtpClockType.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ptp.clock.type"] = filter.CreateFilter(mbc.ResourceAttributes.PtpClockType.MetricsExclude)
	}
	if mbc.ResourceAttributes.PtpSocketPath.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["ptp.socket_path"] = filter.CreateFilter(mbc.ResourceAttributes.PtpSocketPath.MetricsInclude)
	}
	if mbc.ResourceAttributes.PtpSocketPath.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["ptp.socket_path"] = filter.CreateFilter(mbc.ResourceAttributes.PtpSocketPath.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricPtpClockState.emit(ils.Metrics())
	mb.metricPtpGrandmasterInfo.emit(ils.Metrics())
	mb.metricPtpGrandmasterPresent.emit(ils.Metrics())
	mb.metricPtpOffset.emit(ils.Metrics())
	mb.metricPtpPathDelay.emit(ils.Metrics())
	mb.metricPtpPortState.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordPtpClockStateDataPoint adds a data point to ptp.clock.state metric.
func (mb *MetricsBuilder) RecordPtpClockStateDataPoint(ts pcommon.Timestamp, val int64, ptpClockStateAttributeValue string) {
	mb.metricPtpClockState.recordDataPoint(mb.startTime, ts, val, ptpClockStateAttributeValue)
}

// RecordPtpGrandmasterInfoDataPoint adds a data point to ptp.grandmaster.info metric.
func (mb *MetricsBuilder) RecordPtpGrandmasterInfoDataPoint(ts pcommon.Timestamp, val int64, ptpGrandmasterIdentityAttributeValue string) {
	mb.metricPtpGrandmasterInfo.recordDataPoint(mb.startTime, ts, val, ptpGrandmasterIdentityAttributeValue)
}

// RecordPtpGrandmasterPresentDataPoint adds a data point to ptp.grandmaster.present metric.
func (mb *MetricsBuilder) RecordPtpGrandmasterPresentDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricPtpGrandmasterPresent.recordDataPoint(mb.startTime, ts, val)
}

// RecordPtpOffsetDataPoint adds a data point to ptp.offset metric.
func (mb *MetricsBuilder) RecordPtpOffsetDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricPtpOffset.recordDataPoint(mb.startTime, ts, val)
}

// RecordPtpPathDelayDataPoint adds a data point to ptp.path.delay metric.
func (mb *MetricsBuilder) RecordPtpPathDelayDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricPtpPathDelay.recordDataPoint(mb.startTime, ts, val)
}

// RecordPtpPortStateDataPoint adds a data point to ptp.port.state metric.
func (mb *MetricsBuilder) RecordPtpPortStateDataPoint(ts pcommon.Timestamp, val int64, ptpPortIdentityAttributeValue string, ptpPortStateAttributeValue string) {
	mb.metricPtpPortState.recordDataPoint(mb.startTime, ts, val, ptpPortIdentityAttributeValue, ptpPortStateAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
