#!/bin/bash

# Copyright Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

usage() {
  echo "Usage: $0 output_dir binary_path ..."
}
# Find all dependent shared object files for the collectd installation and move
# them into the installation directory

if [[ $# -lt 3 ]]; then
  usage
  exit 1
fi

target_path=$1
mkdir -p $target_path

shift
binary_paths=$@

if [[ ${#binary_paths[@]} == 0 ]]
then
  usage
  exit 1
fi

#echo "First copying given paths to $target_path"
#cp --parents -a -R -L $binary_paths $target_path

echo "Copying dependent libs to $target_path"

find_deps() {
  local paths=$@
  # Run all of the collectd libs/binaries through ldd and pull out the deps
  # We handle libjvm specially so exclude it here.
  find $paths -type f -o -type l -and -executable -or -name "*.so*" | \
    xargs ldd 2>/dev/null | \
    grep -o '/.*' | awk '{print $1}' | grep -v ':$' | grep -v 'libjvm.so' | sort -u
}

copy_file_and_links() {
  local file=$(basename $1)
  local dir=$(dirname $1)
  local target_path=$2
  local ref=$(readlink "${dir}/${file}" 2>/dev/null)
  if [[ -z "$ref" ]]; then
    # file is not a link
    if [[ ! -f "${target_path}/${file}" ]]; then
      cp -a "${dir}/${file}" "$target_path"
      echo "Pulled in ${dir}/${file}"
    fi
  else
    if [[ ! "$ref" =~ ^\/ ]]; then
      # file is a relative link
      ref="${dir}/${ref}"
    fi
    # traverse the links for the source file
    copy_file_and_links "$ref" "$target_path"
    if [[ ! -e "${target_path}/${file}" ]]; then
      # create a relative link in target_path
      (cd "$target_path" && ln -s "$(basename $ref)" "$file" && echo "Created link: $file -> $(readlink ${file})")
    fi
  fi
}

libs=$(find_deps $binary_paths)
# Pulling one level of transitive deps is enough for now
transitive_deps=$(find_deps $libs)
arch=$(uname -m)
if [ "$arch" = "ppc64le" ]; then
    arch="powerpc64le"
fi
for lib in /lib/${arch}-linux-gnu/libnss_* /lib/${arch}-linux-gnu/libnsl* $libs $transitive_deps
do
  copy_file_and_links $lib $target_path
done

echo "Processed $(wc -w <<< $libs) libraries"

echo "Checking for missing lib dependencies..."

# Look for all of the deps now in the target_path and make sure we have them
new_deps=$(find_deps $target_path | sed -e "s!^$target_path!!")
for dep in $new_deps
do
  if ! stat ${target_path}/$(basename ${dep}) >/dev/null; then
    echo "Missing dependency in target dir: $dep" >&2
    exit 1
  fi
done

echo "Everything is there!"
