FROM centos:7

ENV container docker

RUN yum install -y systemd procps initscripts deltarpm

ARG PUPPET_RELEASE="6"
RUN rpm -Uvh https://yum.puppet.com/puppet${PUPPET_RELEASE}-release-el-7.noarch.rpm && \
    yum install -y puppet-agent

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

ENV PATH=/opt/puppetlabs/bin:$PATH

RUN puppet module install puppetlabs-stdlib --version 4.24.0
RUN puppet module install puppet-yum --version 4.3.0

COPY deployments/puppet /etc/puppetlabs/code/environments/production/modules/splunk_otel_collector

CMD ["/usr/sbin/init"]
