FROM ubuntu:20.04

RUN apt-get update &&\
    apt-get install -yq ca-certificates procps systemd wget apt-transport-https libcap2-bin curl gnupg lsb-release

ARG PUPPET_RELEASE="6"
RUN wget https://apt.puppetlabs.com/puppet${PUPPET_RELEASE}-release-focal.deb && \
    dpkg -i puppet${PUPPET_RELEASE}-release-focal.deb && \
    apt-get update && \
    apt-get install -y puppet-agent

ENV PATH=/opt/puppetlabs/bin:$PATH

ENV container docker

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/systemd-update-utmp*

RUN systemctl set-default multi-user.target
ENV init /lib/systemd/systemd

RUN puppet module install puppetlabs-stdlib --version 4.24.0
RUN puppet module install puppetlabs-apt --version 7.0.0

COPY deployments/puppet /etc/puppetlabs/code/environments/production/modules/splunk_otel_connector

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT ["/lib/systemd/systemd"]
