# A opensuse15 image with systemd enabled.  Must be run with:
# `-d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro` flags
FROM opensuse/leap:15

ENV container=docker

# RUN sed -i 's|download.opensuse.org|provo-mirror.opensuse.org|' /etc/zypp/repos.d/*.repo
RUN zypper -n install -l curl dbus-1 systemd-sysvinit tar wget gzip

RUN rpm --import https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406

ARG PUPPET_RELEASE="6"
RUN rpm -Uvh https://yum.puppet.com/puppet${PUPPET_RELEASE}-release-sles-15.noarch.rpm && \
    zypper --gpg-auto-import-keys -n refresh && \
    zypper install -y puppet-agent procps

RUN wget -O /tmp/nodejs.tar.gz https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.gz && \
    mkdir -p /opt/local-repo && \
    tar -C /opt/ -xzf /tmp/nodejs.tar.gz && \
    mv /opt/node* /opt/node

RUN (cd /usr/lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /usr/lib/systemd/system/multi-user.target.wants/*;\
    rm -f /usr/lib/systemd/system/local-fs.target.wants/*; \
    rm -f /usr/lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /usr/lib/systemd/system/basic.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

ENV PATH=/opt/puppetlabs/bin:/opt/node/bin:$PATH

RUN puppet module install puppetlabs-stdlib --version 4.24.0

COPY deployments/puppet /etc/puppetlabs/code/environments/production/modules/splunk_otel_collector

COPY dist/* /opt/local-repo/ && \
     chmod -R a+rwX /opt/local-repo/

CMD ["/sbin/init"]
