FROM amazonlinux:2023

ENV container=docker

RUN yum install -y systemd procps initscripts wget tar

ARG PUPPET_RELEASE="6"
RUN rpm -Uvh https://yum.puppet.com/puppet${PUPPET_RELEASE}-release-el-9.noarch.rpm && \
    yum install -y puppet-agent

RUN wget -O /tmp/nodejs.tar.gz https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.gz && \
    mkdir -p /opt/local-repo && \
    tar -C /opt/ -xzf /tmp/nodejs.tar.gz && \
    mv /opt/node* /opt/node

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

ENV PATH=/opt/puppetlabs/bin:/opt/node/bin:$PATH

RUN puppet module install puppetlabs-stdlib --version 4.24.0
RUN puppet module install puppet-yum --version 4.3.0

COPY deployments/puppet /etc/puppetlabs/code/environments/production/modules/splunk_otel_collector

COPY dist/* /opt/local-repo/
RUN chmod -R a+rwX /opt/local-repo/

CMD ["/usr/sbin/init"]
