FROM quay.io/centos/centos:stream9

ENV container=docker

RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
RUN echo 'fastestmirror=1' >> /etc/yum.conf
RUN dnf install -y systemd procps initscripts wget

ARG PUPPET_RELEASE="6"
RUN rpm -Uvh https://yum.puppet.com/puppet${PUPPET_RELEASE}-release-el-9.noarch.rpm && \
    dnf install -y puppet-agent

RUN wget -O /tmp/nodejs.tar.gz https://nodejs.org/dist/v18.20.8/node-v18.20.8-linux-x64.tar.gz && \
    mkdir -p /opt/local-repo && \
    tar -C /opt/ -xzf /tmp/nodejs.tar.gz && \
    mv /opt/node* /opt/node

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

ENV PATH=/opt/puppetlabs/bin:/opt/node/bin:$PATH

RUN puppet module install puppetlabs-stdlib --version 4.24.0
RUN puppet module install puppet-yum --version 4.3.0

COPY deployments/puppet /etc/puppetlabs/code/environments/production/modules/splunk_otel_collector

COPY dist/* /opt/local-repo/
RUN chmod -R a+rwX /opt/local-repo/
RUN set -eux; \
    dnf install -y libcap createrepo_c || dnf install -y libcap createrepo; \
    CREP=createrepo_c; \
    if ! command -v createrepo_c >/dev/null 2>&1; then \
        CREP=createrepo; \
    fi; \
    $CREP /opt/local-repo; \
    printf '%s\n' \
        "[local-repo]" \
        "name=Local Repository" \
        "baseurl=file:/opt/local-repo" \
        "enabled=1" \
        "gpgcheck=0" \
        "priority=1" \
        > /etc/yum.repos.d/local-repo.repo; \
    dnf clean all || true

CMD ["/usr/sbin/init"]
