receivers:
  splunk_inputs:
    base_dir: /var/splunk_home

exporters:
  splunk_outputs:
    base_dir: /var/splunk_home

service:
  pipelines:
    logs:
      receivers: [splunk_inputs]
      exporters: [splunk_outputs]