FROM opensuse/leap:42

ENV container docker

RUN sed -i 's|download.opensuse.org|ftp5.gwdg.de/pub/opensuse/discontinued|' /etc/zypp/repos.d/*.repo
RUN zypper -n clean && zypper -n refresh
RUN zypper -n install -l curl procps dbus-1 systemd-sysvinit tar wget hostname

ARG CHEF_INSTALLER_ARGS
RUN curl -L https://omnitruck.chef.io/install.sh | sed 's/platform="opensuseleap"/platform="opensuse-leap"/g' | bash -s -- $CHEF_INSTALLER_ARGS

RUN (cd /usr/lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /usr/lib/systemd/system/multi-user.target.wants/*;\
    rm -f /usr/lib/systemd/system/local-fs.target.wants/*; \
    rm -f /usr/lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /usr/lib/systemd/system/basic.target.wants/*;\
    rm -f /usr/lib/systemd/system/anaconda.target.wants/*;

ENV init /sbin/init

COPY deployments/chef /chef-repo/cookbooks/splunk-otel-collector
WORKDIR /chef-repo

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/sbin/init"]
