# A debian image with systemd enabled.  Must be run with:
# `-d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro` flags
FROM debian:bullseye
ARG DOCKER_GID=998

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update &&\
    apt-get install -yq ca-certificates procps systemd iproute2 curl tree

ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN systemctl set-default multi-user.target
ENV init /lib/systemd/systemd

RUN groupadd -g ${DOCKER_GID} docker

COPY --chown=999 service.yaml /etc/otel/collector/config.d/service.yaml
COPY --chown=999 otlp-exporter.yaml /etc/otel/collector/config.d/exporters/otlp-exporter.yaml
COPY --chown=999 prometheus-internal.yaml /etc/otel/collector/config.d/receivers/prometheus-internal.yaml
COPY --chown=999 properties.discovery.yaml /etc/otel/collector/config.d/properties.discovery.yaml
COPY --chown=999 splunk-otel-collector.conf /etc/otel/collector/splunk-otel-collector.conf

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT ["/lib/systemd/systemd"]
