@Library('sym-pipeline@CICD-1772') _

def dockerTag

podTemplate(
  cloud: "kubernetes-build-sre-jenkins-agent",
  inheritFrom: 'jnlp',
  yaml: readTrusted('jenkins/podTemplate.yaml'),
  yamlMergeStrategy: merge()
) {
  node(POD_LABEL) {

    stage('Checkout') {
      shortGitHash = gitCheckout()
      branch = env.BRANCH_NAME.replaceAll(/[\.-]/, "_")
      dockerTag = "${branch}-${env.BUILD_NUMBER}-${shortGitHash}"
    }

    buildGolangApp {
      buildDockerImage = true
      dockerRepository = "us-east4-docker.pkg.dev/sym-prod-mr-tools-01/sre-docker-us-east4"
      dockerTag = dockerTag
    }
  }
}