// Code generated by monitor-code-gen. DO NOT EDIT.

package uptime

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "collectd/uptime"

var groupSet = map[string]bool{}

const (
	uptime = "uptime"
)

var metricSet = map[string]monitors.MetricInfo{
	uptime: {Type: datapoint.Gauge},
}

var defaultMetrics = map[string]bool{
	uptime: true,
}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "collectd/uptime",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
