// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/signalfxgatewayprometheusremotewrite component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signalfxgatewayprometheusremotewrite")
	ScopeName = "github.com/signalfx/splunk-otel-collector/internal/receiver/signalfxgatewayprometheusremotewritereceiver"
)

const (
	MetricsStability = component.StabilityLevelDeprecated
)
