receivers:
  promql:
    endpoint: http://prometheus-auth:8080/api/v1/query
    collection_interval: 10s
    queries:
      - query: up
        metric_name_fallback: prometheus_up
    auth:
      authenticator: bearertokenauth

exporters:
  debug:
    verbosity: detailed

extensions:
  bearertokenauth:
    token: ${env:PROMETHEUS_BEARER_TOKEN}

service:
  extensions: [bearertokenauth]
  pipelines:
    metrics:
      receivers: [promql]
      exporters: [debug]
