// Code generated by monitor-code-gen. DO NOT EDIT.

package scheduler

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "kubernetes-scheduler"

var groupSet = map[string]bool{}

const (
	apiserverAuditEventTotal                                      = "apiserver_audit_event_total"
	apiserverAuditRequestsRejectedTotal                           = "apiserver_audit_requests_rejected_total"
	apiserverClientCertificateExpirationSeconds                   = "apiserver_client_certificate_expiration_seconds"
	apiserverClientCertificateExpirationSecondsBucket             = "apiserver_client_certificate_expiration_seconds_bucket"
	apiserverClientCertificateExpirationSecondsCount              = "apiserver_client_certificate_expiration_seconds_count"
	apiserverStorageDataKeyGenerationDurationSeconds              = "apiserver_storage_data_key_generation_duration_seconds"
	apiserverStorageDataKeyGenerationDurationSecondsBucket        = "apiserver_storage_data_key_generation_duration_seconds_bucket"
	apiserverStorageDataKeyGenerationDurationSecondsCount         = "apiserver_storage_data_key_generation_duration_seconds_count"
	apiserverStorageDataKeyGenerationFailuresTotal                = "apiserver_storage_data_key_generation_failures_total"
	apiserverStorageDataKeyGenerationLatenciesMicroseconds        = "apiserver_storage_data_key_generation_latencies_microseconds"
	apiserverStorageDataKeyGenerationLatenciesMicrosecondsBucket  = "apiserver_storage_data_key_generation_latencies_microseconds_bucket"
	apiserverStorageDataKeyGenerationLatenciesMicrosecondsCount   = "apiserver_storage_data_key_generation_latencies_microseconds_count"
	apiserverStorageEnvelopeTransformationCacheMissesTotal        = "apiserver_storage_envelope_transformation_cache_misses_total"
	goGcDurationSeconds                                           = "go_gc_duration_seconds"
	goGcDurationSecondsCount                                      = "go_gc_duration_seconds_count"
	goGcDurationSecondsQuantile                                   = "go_gc_duration_seconds_quantile"
	goGoroutines                                                  = "go_goroutines"
	goInfo                                                        = "go_info"
	goMemstatsAllocBytes                                          = "go_memstats_alloc_bytes"
	goMemstatsAllocBytesTotal                                     = "go_memstats_alloc_bytes_total"
	goMemstatsBuckHashSysBytes                                    = "go_memstats_buck_hash_sys_bytes"
	goMemstatsFreesTotal                                          = "go_memstats_frees_total"
	goMemstatsGcCPUFraction                                       = "go_memstats_gc_cpu_fraction"
	goMemstatsGcSysBytes                                          = "go_memstats_gc_sys_bytes"
	goMemstatsHeapAllocBytes                                      = "go_memstats_heap_alloc_bytes"
	goMemstatsHeapIdleBytes                                       = "go_memstats_heap_idle_bytes"
	goMemstatsHeapInuseBytes                                      = "go_memstats_heap_inuse_bytes"
	goMemstatsHeapObjects                                         = "go_memstats_heap_objects"
	goMemstatsHeapReleasedBytes                                   = "go_memstats_heap_released_bytes"
	goMemstatsHeapSysBytes                                        = "go_memstats_heap_sys_bytes"
	goMemstatsLastGcTimeSeconds                                   = "go_memstats_last_gc_time_seconds"
	goMemstatsLookupsTotal                                        = "go_memstats_lookups_total"
	goMemstatsMallocsTotal                                        = "go_memstats_mallocs_total"
	goMemstatsMcacheInuseBytes                                    = "go_memstats_mcache_inuse_bytes"
	goMemstatsMcacheSysBytes                                      = "go_memstats_mcache_sys_bytes"
	goMemstatsMspanInuseBytes                                     = "go_memstats_mspan_inuse_bytes"
	goMemstatsMspanSysBytes                                       = "go_memstats_mspan_sys_bytes"
	goMemstatsNextGcBytes                                         = "go_memstats_next_gc_bytes"
	goMemstatsOtherSysBytes                                       = "go_memstats_other_sys_bytes"
	goMemstatsStackInuseBytes                                     = "go_memstats_stack_inuse_bytes"
	goMemstatsStackSysBytes                                       = "go_memstats_stack_sys_bytes"
	goMemstatsSysBytes                                            = "go_memstats_sys_bytes"
	goThreads                                                     = "go_threads"
	httpRequestDurationMicroseconds                               = "http_request_duration_microseconds"
	httpRequestDurationMicrosecondsCount                          = "http_request_duration_microseconds_count"
	httpRequestDurationMicrosecondsQuantile                       = "http_request_duration_microseconds_quantile"
	httpRequestSizeBytes                                          = "http_request_size_bytes"
	httpRequestSizeBytesCount                                     = "http_request_size_bytes_count"
	httpRequestSizeBytesQuantile                                  = "http_request_size_bytes_quantile"
	httpRequestsTotal                                             = "http_requests_total"
	httpResponseSizeBytes                                         = "http_response_size_bytes"
	httpResponseSizeBytesCount                                    = "http_response_size_bytes_count"
	httpResponseSizeBytesQuantile                                 = "http_response_size_bytes_quantile"
	kubernetesBuildInfo                                           = "kubernetes_build_info"
	leaderElectionMasterStatus                                    = "leader_election_master_status"
	processCPUSecondsTotal                                        = "process_cpu_seconds_total"
	processMaxFds                                                 = "process_max_fds"
	processOpenFds                                                = "process_open_fds"
	processResidentMemoryBytes                                    = "process_resident_memory_bytes"
	processStartTimeSeconds                                       = "process_start_time_seconds"
	processVirtualMemoryBytes                                     = "process_virtual_memory_bytes"
	processVirtualMemoryMaxBytes                                  = "process_virtual_memory_max_bytes"
	restClientRequestDurationSeconds                              = "rest_client_request_duration_seconds"
	restClientRequestDurationSecondsBucket                        = "rest_client_request_duration_seconds_bucket"
	restClientRequestDurationSecondsCount                         = "rest_client_request_duration_seconds_count"
	restClientRequestLatencySeconds                               = "rest_client_request_latency_seconds"
	restClientRequestLatencySecondsBucket                         = "rest_client_request_latency_seconds_bucket"
	restClientRequestLatencySecondsCount                          = "rest_client_request_latency_seconds_count"
	restClientRequestsTotal                                       = "rest_client_requests_total"
	schedulerBindingDurationSeconds                               = "scheduler_binding_duration_seconds"
	schedulerBindingDurationSecondsBucket                         = "scheduler_binding_duration_seconds_bucket"
	schedulerBindingDurationSecondsCount                          = "scheduler_binding_duration_seconds_count"
	schedulerBindingLatencyMicroseconds                           = "scheduler_binding_latency_microseconds"
	schedulerBindingLatencyMicrosecondsBucket                     = "scheduler_binding_latency_microseconds_bucket"
	schedulerBindingLatencyMicrosecondsCount                      = "scheduler_binding_latency_microseconds_count"
	schedulerE2eSchedulingDurationSeconds                         = "scheduler_e2e_scheduling_duration_seconds"
	schedulerE2eSchedulingDurationSecondsBucket                   = "scheduler_e2e_scheduling_duration_seconds_bucket"
	schedulerE2eSchedulingDurationSecondsCount                    = "scheduler_e2e_scheduling_duration_seconds_count"
	schedulerE2eSchedulingLatencyMicroseconds                     = "scheduler_e2e_scheduling_latency_microseconds"
	schedulerE2eSchedulingLatencyMicrosecondsBucket               = "scheduler_e2e_scheduling_latency_microseconds_bucket"
	schedulerE2eSchedulingLatencyMicrosecondsCount                = "scheduler_e2e_scheduling_latency_microseconds_count"
	schedulerPendingPods                                          = "scheduler_pending_pods"
	schedulerPodPreemptionVictims                                 = "scheduler_pod_preemption_victims"
	schedulerScheduleAttemptsTotal                                = "scheduler_schedule_attempts_total"
	schedulerSchedulingAlgorithmDurationSeconds                   = "scheduler_scheduling_algorithm_duration_seconds"
	schedulerSchedulingAlgorithmDurationSecondsBucket             = "scheduler_scheduling_algorithm_duration_seconds_bucket"
	schedulerSchedulingAlgorithmDurationSecondsCount              = "scheduler_scheduling_algorithm_duration_seconds_count"
	schedulerSchedulingAlgorithmLatencyMicroseconds               = "scheduler_scheduling_algorithm_latency_microseconds"
	schedulerSchedulingAlgorithmLatencyMicrosecondsBucket         = "scheduler_scheduling_algorithm_latency_microseconds_bucket"
	schedulerSchedulingAlgorithmLatencyMicrosecondsCount          = "scheduler_scheduling_algorithm_latency_microseconds_count"
	schedulerSchedulingAlgorithmPredicateEvaluation               = "scheduler_scheduling_algorithm_predicate_evaluation"
	schedulerSchedulingAlgorithmPredicateEvaluationBucket         = "scheduler_scheduling_algorithm_predicate_evaluation_bucket"
	schedulerSchedulingAlgorithmPredicateEvaluationCount          = "scheduler_scheduling_algorithm_predicate_evaluation_count"
	schedulerSchedulingAlgorithmPredicateEvaluationSeconds        = "scheduler_scheduling_algorithm_predicate_evaluation_seconds"
	schedulerSchedulingAlgorithmPredicateEvaluationSecondsBucket  = "scheduler_scheduling_algorithm_predicate_evaluation_seconds_bucket"
	schedulerSchedulingAlgorithmPredicateEvaluationSecondsCount   = "scheduler_scheduling_algorithm_predicate_evaluation_seconds_count"
	schedulerSchedulingAlgorithmPreemptionEvaluation              = "scheduler_scheduling_algorithm_preemption_evaluation"
	schedulerSchedulingAlgorithmPreemptionEvaluationBucket        = "scheduler_scheduling_algorithm_preemption_evaluation_bucket"
	schedulerSchedulingAlgorithmPreemptionEvaluationCount         = "scheduler_scheduling_algorithm_preemption_evaluation_count"
	schedulerSchedulingAlgorithmPreemptionEvaluationSeconds       = "scheduler_scheduling_algorithm_preemption_evaluation_seconds"
	schedulerSchedulingAlgorithmPreemptionEvaluationSecondsBucket = "scheduler_scheduling_algorithm_preemption_evaluation_seconds_bucket"
	schedulerSchedulingAlgorithmPreemptionEvaluationSecondsCount  = "scheduler_scheduling_algorithm_preemption_evaluation_seconds_count"
	schedulerSchedulingAlgorithmPriorityEvaluation                = "scheduler_scheduling_algorithm_priority_evaluation"
	schedulerSchedulingAlgorithmPriorityEvaluationBucket          = "scheduler_scheduling_algorithm_priority_evaluation_bucket"
	schedulerSchedulingAlgorithmPriorityEvaluationCount           = "scheduler_scheduling_algorithm_priority_evaluation_count"
	schedulerSchedulingAlgorithmPriorityEvaluationSeconds         = "scheduler_scheduling_algorithm_priority_evaluation_seconds"
	schedulerSchedulingAlgorithmPriorityEvaluationSecondsBucket   = "scheduler_scheduling_algorithm_priority_evaluation_seconds_bucket"
	schedulerSchedulingAlgorithmPriorityEvaluationSecondsCount    = "scheduler_scheduling_algorithm_priority_evaluation_seconds_count"
	schedulerSchedulingDurationSeconds                            = "scheduler_scheduling_duration_seconds"
	schedulerSchedulingDurationSecondsCount                       = "scheduler_scheduling_duration_seconds_count"
	schedulerSchedulingDurationSecondsQuantile                    = "scheduler_scheduling_duration_seconds_quantile"
	schedulerSchedulingLatencySeconds                             = "scheduler_scheduling_latency_seconds"
	schedulerSchedulingLatencySecondsCount                        = "scheduler_scheduling_latency_seconds_count"
	schedulerSchedulingLatencySecondsQuantile                     = "scheduler_scheduling_latency_seconds_quantile"
	schedulerTotalPreemptionAttempts                              = "scheduler_total_preemption_attempts"
	schedulerVolumeSchedulingDurationSeconds                      = "scheduler_volume_scheduling_duration_seconds"
	schedulerVolumeSchedulingDurationSecondsBucket                = "scheduler_volume_scheduling_duration_seconds_bucket"
	schedulerVolumeSchedulingDurationSecondsCount                 = "scheduler_volume_scheduling_duration_seconds_count"
)

var metricSet = map[string]monitors.MetricInfo{
	apiserverAuditEventTotal:                                      {Type: datapoint.Counter},
	apiserverAuditRequestsRejectedTotal:                           {Type: datapoint.Counter},
	apiserverClientCertificateExpirationSeconds:                   {Type: datapoint.Counter},
	apiserverClientCertificateExpirationSecondsBucket:             {Type: datapoint.Counter},
	apiserverClientCertificateExpirationSecondsCount:              {Type: datapoint.Counter},
	apiserverStorageDataKeyGenerationDurationSeconds:              {Type: datapoint.Counter},
	apiserverStorageDataKeyGenerationDurationSecondsBucket:        {Type: datapoint.Counter},
	apiserverStorageDataKeyGenerationDurationSecondsCount:         {Type: datapoint.Counter},
	apiserverStorageDataKeyGenerationFailuresTotal:                {Type: datapoint.Counter},
	apiserverStorageDataKeyGenerationLatenciesMicroseconds:        {Type: datapoint.Counter},
	apiserverStorageDataKeyGenerationLatenciesMicrosecondsBucket:  {Type: datapoint.Counter},
	apiserverStorageDataKeyGenerationLatenciesMicrosecondsCount:   {Type: datapoint.Counter},
	apiserverStorageEnvelopeTransformationCacheMissesTotal:        {Type: datapoint.Counter},
	goGcDurationSeconds:                                           {Type: datapoint.Counter},
	goGcDurationSecondsCount:                                      {Type: datapoint.Counter},
	goGcDurationSecondsQuantile:                                   {Type: datapoint.Gauge},
	goGoroutines:                                                  {Type: datapoint.Gauge},
	goInfo:                                                        {Type: datapoint.Gauge},
	goMemstatsAllocBytes:                                          {Type: datapoint.Gauge},
	goMemstatsAllocBytesTotal:                                     {Type: datapoint.Counter},
	goMemstatsBuckHashSysBytes:                                    {Type: datapoint.Gauge},
	goMemstatsFreesTotal:                                          {Type: datapoint.Counter},
	goMemstatsGcCPUFraction:                                       {Type: datapoint.Gauge},
	goMemstatsGcSysBytes:                                          {Type: datapoint.Gauge},
	goMemstatsHeapAllocBytes:                                      {Type: datapoint.Gauge},
	goMemstatsHeapIdleBytes:                                       {Type: datapoint.Gauge},
	goMemstatsHeapInuseBytes:                                      {Type: datapoint.Gauge},
	goMemstatsHeapObjects:                                         {Type: datapoint.Gauge},
	goMemstatsHeapReleasedBytes:                                   {Type: datapoint.Gauge},
	goMemstatsHeapSysBytes:                                        {Type: datapoint.Gauge},
	goMemstatsLastGcTimeSeconds:                                   {Type: datapoint.Gauge},
	goMemstatsLookupsTotal:                                        {Type: datapoint.Counter},
	goMemstatsMallocsTotal:                                        {Type: datapoint.Counter},
	goMemstatsMcacheInuseBytes:                                    {Type: datapoint.Gauge},
	goMemstatsMcacheSysBytes:                                      {Type: datapoint.Gauge},
	goMemstatsMspanInuseBytes:                                     {Type: datapoint.Gauge},
	goMemstatsMspanSysBytes:                                       {Type: datapoint.Gauge},
	goMemstatsNextGcBytes:                                         {Type: datapoint.Gauge},
	goMemstatsOtherSysBytes:                                       {Type: datapoint.Gauge},
	goMemstatsStackInuseBytes:                                     {Type: datapoint.Gauge},
	goMemstatsStackSysBytes:                                       {Type: datapoint.Gauge},
	goMemstatsSysBytes:                                            {Type: datapoint.Gauge},
	goThreads:                                                     {Type: datapoint.Gauge},
	httpRequestDurationMicroseconds:                               {Type: datapoint.Counter},
	httpRequestDurationMicrosecondsCount:                          {Type: datapoint.Counter},
	httpRequestDurationMicrosecondsQuantile:                       {Type: datapoint.Gauge},
	httpRequestSizeBytes:                                          {Type: datapoint.Counter},
	httpRequestSizeBytesCount:                                     {Type: datapoint.Counter},
	httpRequestSizeBytesQuantile:                                  {Type: datapoint.Gauge},
	httpRequestsTotal:                                             {Type: datapoint.Counter},
	httpResponseSizeBytes:                                         {Type: datapoint.Counter},
	httpResponseSizeBytesCount:                                    {Type: datapoint.Counter},
	httpResponseSizeBytesQuantile:                                 {Type: datapoint.Gauge},
	kubernetesBuildInfo:                                           {Type: datapoint.Gauge},
	leaderElectionMasterStatus:                                    {Type: datapoint.Gauge},
	processCPUSecondsTotal:                                        {Type: datapoint.Counter},
	processMaxFds:                                                 {Type: datapoint.Gauge},
	processOpenFds:                                                {Type: datapoint.Gauge},
	processResidentMemoryBytes:                                    {Type: datapoint.Gauge},
	processStartTimeSeconds:                                       {Type: datapoint.Gauge},
	processVirtualMemoryBytes:                                     {Type: datapoint.Gauge},
	processVirtualMemoryMaxBytes:                                  {Type: datapoint.Gauge},
	restClientRequestDurationSeconds:                              {Type: datapoint.Counter},
	restClientRequestDurationSecondsBucket:                        {Type: datapoint.Counter},
	restClientRequestDurationSecondsCount:                         {Type: datapoint.Counter},
	restClientRequestLatencySeconds:                               {Type: datapoint.Counter},
	restClientRequestLatencySecondsBucket:                         {Type: datapoint.Counter},
	restClientRequestLatencySecondsCount:                          {Type: datapoint.Counter},
	restClientRequestsTotal:                                       {Type: datapoint.Counter},
	schedulerBindingDurationSeconds:                               {Type: datapoint.Counter},
	schedulerBindingDurationSecondsBucket:                         {Type: datapoint.Counter},
	schedulerBindingDurationSecondsCount:                          {Type: datapoint.Counter},
	schedulerBindingLatencyMicroseconds:                           {Type: datapoint.Counter},
	schedulerBindingLatencyMicrosecondsBucket:                     {Type: datapoint.Counter},
	schedulerBindingLatencyMicrosecondsCount:                      {Type: datapoint.Counter},
	schedulerE2eSchedulingDurationSeconds:                         {Type: datapoint.Counter},
	schedulerE2eSchedulingDurationSecondsBucket:                   {Type: datapoint.Counter},
	schedulerE2eSchedulingDurationSecondsCount:                    {Type: datapoint.Counter},
	schedulerE2eSchedulingLatencyMicroseconds:                     {Type: datapoint.Counter},
	schedulerE2eSchedulingLatencyMicrosecondsBucket:               {Type: datapoint.Counter},
	schedulerE2eSchedulingLatencyMicrosecondsCount:                {Type: datapoint.Counter},
	schedulerPendingPods:                                          {Type: datapoint.Gauge},
	schedulerPodPreemptionVictims:                                 {Type: datapoint.Gauge},
	schedulerScheduleAttemptsTotal:                                {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmDurationSeconds:                   {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmDurationSecondsBucket:             {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmDurationSecondsCount:              {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmLatencyMicroseconds:               {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmLatencyMicrosecondsBucket:         {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmLatencyMicrosecondsCount:          {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPredicateEvaluation:               {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPredicateEvaluationBucket:         {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPredicateEvaluationCount:          {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPredicateEvaluationSeconds:        {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPredicateEvaluationSecondsBucket:  {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPredicateEvaluationSecondsCount:   {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPreemptionEvaluation:              {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPreemptionEvaluationBucket:        {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPreemptionEvaluationCount:         {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPreemptionEvaluationSeconds:       {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPreemptionEvaluationSecondsBucket: {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPreemptionEvaluationSecondsCount:  {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPriorityEvaluation:                {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPriorityEvaluationBucket:          {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPriorityEvaluationCount:           {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPriorityEvaluationSeconds:         {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPriorityEvaluationSecondsBucket:   {Type: datapoint.Counter},
	schedulerSchedulingAlgorithmPriorityEvaluationSecondsCount:    {Type: datapoint.Counter},
	schedulerSchedulingDurationSeconds:                            {Type: datapoint.Counter},
	schedulerSchedulingDurationSecondsCount:                       {Type: datapoint.Counter},
	schedulerSchedulingDurationSecondsQuantile:                    {Type: datapoint.Gauge},
	schedulerSchedulingLatencySeconds:                             {Type: datapoint.Counter},
	schedulerSchedulingLatencySecondsCount:                        {Type: datapoint.Counter},
	schedulerSchedulingLatencySecondsQuantile:                     {Type: datapoint.Gauge},
	schedulerTotalPreemptionAttempts:                              {Type: datapoint.Counter},
	schedulerVolumeSchedulingDurationSeconds:                      {Type: datapoint.Counter},
	schedulerVolumeSchedulingDurationSecondsBucket:                {Type: datapoint.Counter},
	schedulerVolumeSchedulingDurationSecondsCount:                 {Type: datapoint.Counter},
}

var defaultMetrics = map[string]bool{
	restClientRequestsTotal:                         true,
	schedulerBindingDurationSeconds:                 true,
	schedulerBindingLatencyMicroseconds:             true,
	schedulerE2eSchedulingDurationSeconds:           true,
	schedulerE2eSchedulingLatencyMicroseconds:       true,
	schedulerSchedulingAlgorithmDurationSeconds:     true,
	schedulerSchedulingAlgorithmLatencyMicroseconds: true,
}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "kubernetes-scheduler",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
