receiver_id: prometheus/otelcol
service_type: prometheus
properties_tmpl: |
  enabled: false
  rule:
    host_observer: type == "hostport" and command contains "otelcol"
  config:
    default:
      config:
        scrape_configs:
          - job_name: 'otelcol'
            scrape_interval: 10s
            static_configs:
              - targets: ['`endpoint`']
status:
  metrics:
    - status: successful
      regexp: "^otelcol_process_uptime$"
      message: Successfully connected to prometheus server
  statements:
    - status: failed
      strict: "Failed to scrape Prometheus endpoint"
      message: Port appears to not be serving prometheus metrics
    - status: failed
      regexp: "Failed to scrape Prometheus endpoint"
      message: Port appears to not be serving prometheus metrics
