// Code generated by monitor-code-gen. DO NOT EDIT.

package prometheus

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "prometheus/prometheus"

var groupSet = map[string]bool{}

const (
	netConntrackDialerConnAttemptedTotal                 = "net_conntrack_dialer_conn_attempted_total"
	netConntrackDialerConnClosedTotal                    = "net_conntrack_dialer_conn_closed_total"
	netConntrackDialerConnEstablishedTotal               = "net_conntrack_dialer_conn_established_total"
	netConntrackDialerConnFailedTotal                    = "net_conntrack_dialer_conn_failed_total"
	netConntrackListenerConnAcceptedTotal                = "net_conntrack_listener_conn_accepted_total"
	netConntrackListenerConnClosedTotal                  = "net_conntrack_listener_conn_closed_total"
	prometheusAPIRemoteReadQueries                       = "prometheus_api_remote_read_queries"
	prometheusBuildInfo                                  = "prometheus_build_info"
	prometheusConfigLastReloadSuccessTimestampSeconds    = "prometheus_config_last_reload_success_timestamp_seconds"
	prometheusConfigLastReloadSuccessful                 = "prometheus_config_last_reload_successful"
	prometheusEngineQueries                              = "prometheus_engine_queries"
	prometheusEngineQueriesConcurrentMax                 = "prometheus_engine_queries_concurrent_max"
	prometheusEngineQueryDurationSeconds                 = "prometheus_engine_query_duration_seconds"
	prometheusEngineQueryDurationSecondsCount            = "prometheus_engine_query_duration_seconds_count"
	prometheusHTTPRequestDurationSeconds                 = "prometheus_http_request_duration_seconds"
	prometheusHTTPRequestDurationSecondsBucket           = "prometheus_http_request_duration_seconds_bucket"
	prometheusHTTPRequestDurationSecondsCount            = "prometheus_http_request_duration_seconds_count"
	prometheusHTTPResponseSizeBytes                      = "prometheus_http_response_size_bytes"
	prometheusHTTPResponseSizeBytesBucket                = "prometheus_http_response_size_bytes_bucket"
	prometheusHTTPResponseSizeBytesCount                 = "prometheus_http_response_size_bytes_count"
	prometheusNotificationsAlertmanagersDiscovered       = "prometheus_notifications_alertmanagers_discovered"
	prometheusNotificationsDroppedTotal                  = "prometheus_notifications_dropped_total"
	prometheusNotificationsQueueCapacity                 = "prometheus_notifications_queue_capacity"
	prometheusNotificationsQueueLength                   = "prometheus_notifications_queue_length"
	prometheusRuleEvaluationDurationSeconds              = "prometheus_rule_evaluation_duration_seconds"
	prometheusRuleEvaluationDurationSecondsCount         = "prometheus_rule_evaluation_duration_seconds_count"
	prometheusRuleEvaluationFailuresTotal                = "prometheus_rule_evaluation_failures_total"
	prometheusRuleGroupDurationSeconds                   = "prometheus_rule_group_duration_seconds"
	prometheusRuleGroupDurationSecondsCount              = "prometheus_rule_group_duration_seconds_count"
	prometheusRuleGroupIntervalSeconds                   = "prometheus_rule_group_interval_seconds"
	prometheusRuleGroupIterationsMissedTotal             = "prometheus_rule_group_iterations_missed_total"
	prometheusRuleGroupIterationsTotal                   = "prometheus_rule_group_iterations_total"
	prometheusRuleGroupLastDurationSeconds               = "prometheus_rule_group_last_duration_seconds"
	prometheusSdAzureRefreshDurationSeconds              = "prometheus_sd_azure_refresh_duration_seconds"
	prometheusSdAzureRefreshDurationSecondsCount         = "prometheus_sd_azure_refresh_duration_seconds_count"
	prometheusSdAzureRefreshFailuresTotal                = "prometheus_sd_azure_refresh_failures_total"
	prometheusSdConfigsFailedTotal                       = "prometheus_sd_configs_failed_total"
	prometheusSdConsulRPCDurationSeconds                 = "prometheus_sd_consul_rpc_duration_seconds"
	prometheusSdConsulRPCDurationSecondsCount            = "prometheus_sd_consul_rpc_duration_seconds_count"
	prometheusSdConsulRPCFailuresTotal                   = "prometheus_sd_consul_rpc_failures_total"
	prometheusSdDiscoveredTargets                        = "prometheus_sd_discovered_targets"
	prometheusSdDNSLookupFailuresTotal                   = "prometheus_sd_dns_lookup_failures_total"
	prometheusSdDNSLookupsTotal                          = "prometheus_sd_dns_lookups_total"
	prometheusSdEc2RefreshDurationSeconds                = "prometheus_sd_ec2_refresh_duration_seconds"
	prometheusSdEc2RefreshDurationSecondsCount           = "prometheus_sd_ec2_refresh_duration_seconds_count"
	prometheusSdEc2RefreshFailuresTotal                  = "prometheus_sd_ec2_refresh_failures_total"
	prometheusSdFileReadErrorsTotal                      = "prometheus_sd_file_read_errors_total"
	prometheusSdFileScanDurationSeconds                  = "prometheus_sd_file_scan_duration_seconds"
	prometheusSdFileScanDurationSecondsCount             = "prometheus_sd_file_scan_duration_seconds_count"
	prometheusSdGceRefreshDuration                       = "prometheus_sd_gce_refresh_duration"
	prometheusSdGceRefreshDurationCount                  = "prometheus_sd_gce_refresh_duration_count"
	prometheusSdGceRefreshFailuresTotal                  = "prometheus_sd_gce_refresh_failures_total"
	prometheusSdKubernetesCacheLastResourceVersion       = "prometheus_sd_kubernetes_cache_last_resource_version"
	prometheusSdKubernetesCacheListDurationSeconds       = "prometheus_sd_kubernetes_cache_list_duration_seconds"
	prometheusSdKubernetesCacheListDurationSecondsCount  = "prometheus_sd_kubernetes_cache_list_duration_seconds_count"
	prometheusSdKubernetesCacheListItems                 = "prometheus_sd_kubernetes_cache_list_items"
	prometheusSdKubernetesCacheListItemsCount            = "prometheus_sd_kubernetes_cache_list_items_count"
	prometheusSdKubernetesCacheListTotal                 = "prometheus_sd_kubernetes_cache_list_total"
	prometheusSdKubernetesCacheShortWatchesTotal         = "prometheus_sd_kubernetes_cache_short_watches_total"
	prometheusSdKubernetesCacheWatchDurationSeconds      = "prometheus_sd_kubernetes_cache_watch_duration_seconds"
	prometheusSdKubernetesCacheWatchDurationSecondsCount = "prometheus_sd_kubernetes_cache_watch_duration_seconds_count"
	prometheusSdKubernetesCacheWatchEvents               = "prometheus_sd_kubernetes_cache_watch_events"
	prometheusSdKubernetesCacheWatchEventsCount          = "prometheus_sd_kubernetes_cache_watch_events_count"
	prometheusSdKubernetesCacheWatchesTotal              = "prometheus_sd_kubernetes_cache_watches_total"
	prometheusSdKubernetesEventsTotal                    = "prometheus_sd_kubernetes_events_total"
	prometheusSdMarathonRefreshDurationSeconds           = "prometheus_sd_marathon_refresh_duration_seconds"
	prometheusSdMarathonRefreshDurationSecondsCount      = "prometheus_sd_marathon_refresh_duration_seconds_count"
	prometheusSdMarathonRefreshFailuresTotal             = "prometheus_sd_marathon_refresh_failures_total"
	prometheusSdOpenstackRefreshDurationSeconds          = "prometheus_sd_openstack_refresh_duration_seconds"
	prometheusSdOpenstackRefreshDurationSecondsCount     = "prometheus_sd_openstack_refresh_duration_seconds_count"
	prometheusSdOpenstackRefreshFailuresTotal            = "prometheus_sd_openstack_refresh_failures_total"
	prometheusSdReceivedUpdatesTotal                     = "prometheus_sd_received_updates_total"
	prometheusSdTritonRefreshDurationSeconds             = "prometheus_sd_triton_refresh_duration_seconds"
	prometheusSdTritonRefreshDurationSecondsCount        = "prometheus_sd_triton_refresh_duration_seconds_count"
	prometheusSdTritonRefreshFailuresTotal               = "prometheus_sd_triton_refresh_failures_total"
	prometheusSdUpdatesDelayedTotal                      = "prometheus_sd_updates_delayed_total"
	prometheusSdUpdatesTotal                             = "prometheus_sd_updates_total"
	prometheusTargetIntervalLengthSeconds                = "prometheus_target_interval_length_seconds"
	prometheusTargetIntervalLengthSecondsCount           = "prometheus_target_interval_length_seconds_count"
	prometheusTargetScrapePoolSyncTotal                  = "prometheus_target_scrape_pool_sync_total"
	prometheusTargetScrapesExceededSampleLimitTotal      = "prometheus_target_scrapes_exceeded_sample_limit_total"
	prometheusTargetScrapesSampleDuplicateTimestampTotal = "prometheus_target_scrapes_sample_duplicate_timestamp_total"
	prometheusTargetScrapesSampleOutOfBoundsTotal        = "prometheus_target_scrapes_sample_out_of_bounds_total"
	prometheusTargetScrapesSampleOutOfOrderTotal         = "prometheus_target_scrapes_sample_out_of_order_total"
	prometheusTargetSyncLengthSeconds                    = "prometheus_target_sync_length_seconds"
	prometheusTargetSyncLengthSecondsCount               = "prometheus_target_sync_length_seconds_count"
	prometheusTreecacheWatcherGoroutines                 = "prometheus_treecache_watcher_goroutines"
	prometheusTreecacheZookeeperFailuresTotal            = "prometheus_treecache_zookeeper_failures_total"
	prometheusTsdbBlocksLoaded                           = "prometheus_tsdb_blocks_loaded"
	prometheusTsdbCheckpointCreationsFailedTotal         = "prometheus_tsdb_checkpoint_creations_failed_total"
	prometheusTsdbCheckpointCreationsTotal               = "prometheus_tsdb_checkpoint_creations_total"
	prometheusTsdbCheckpointDeletionsFailedTotal         = "prometheus_tsdb_checkpoint_deletions_failed_total"
	prometheusTsdbCheckpointDeletionsTotal               = "prometheus_tsdb_checkpoint_deletions_total"
	prometheusTsdbCompactionChunkRangeSeconds            = "prometheus_tsdb_compaction_chunk_range_seconds"
	prometheusTsdbCompactionChunkRangeSecondsBucket      = "prometheus_tsdb_compaction_chunk_range_seconds_bucket"
	prometheusTsdbCompactionChunkRangeSecondsCount       = "prometheus_tsdb_compaction_chunk_range_seconds_count"
	prometheusTsdbCompactionChunkSamples                 = "prometheus_tsdb_compaction_chunk_samples"
	prometheusTsdbCompactionChunkSamplesBucket           = "prometheus_tsdb_compaction_chunk_samples_bucket"
	prometheusTsdbCompactionChunkSamplesCount            = "prometheus_tsdb_compaction_chunk_samples_count"
	prometheusTsdbCompactionChunkSizeBytes               = "prometheus_tsdb_compaction_chunk_size_bytes"
	prometheusTsdbCompactionChunkSizeBytesBucket         = "prometheus_tsdb_compaction_chunk_size_bytes_bucket"
	prometheusTsdbCompactionChunkSizeBytesCount          = "prometheus_tsdb_compaction_chunk_size_bytes_count"
	prometheusTsdbCompactionDurationSeconds              = "prometheus_tsdb_compaction_duration_seconds"
	prometheusTsdbCompactionDurationSecondsBucket        = "prometheus_tsdb_compaction_duration_seconds_bucket"
	prometheusTsdbCompactionDurationSecondsCount         = "prometheus_tsdb_compaction_duration_seconds_count"
	prometheusTsdbCompactionsFailedTotal                 = "prometheus_tsdb_compactions_failed_total"
	prometheusTsdbCompactionsTotal                       = "prometheus_tsdb_compactions_total"
	prometheusTsdbCompactionsTriggeredTotal              = "prometheus_tsdb_compactions_triggered_total"
	prometheusTsdbHeadActiveAppenders                    = "prometheus_tsdb_head_active_appenders"
	prometheusTsdbHeadChunks                             = "prometheus_tsdb_head_chunks"
	prometheusTsdbHeadChunksCreatedTotal                 = "prometheus_tsdb_head_chunks_created_total"
	prometheusTsdbHeadChunksRemovedTotal                 = "prometheus_tsdb_head_chunks_removed_total"
	prometheusTsdbHeadGcDurationSeconds                  = "prometheus_tsdb_head_gc_duration_seconds"
	prometheusTsdbHeadGcDurationSecondsCount             = "prometheus_tsdb_head_gc_duration_seconds_count"
	prometheusTsdbHeadMaxTime                            = "prometheus_tsdb_head_max_time"
	prometheusTsdbHeadMinTime                            = "prometheus_tsdb_head_min_time"
	prometheusTsdbHeadSamplesAppendedTotal               = "prometheus_tsdb_head_samples_appended_total"
	prometheusTsdbHeadSeries                             = "prometheus_tsdb_head_series"
	prometheusTsdbHeadSeriesCreatedTotal                 = "prometheus_tsdb_head_series_created_total"
	prometheusTsdbHeadSeriesNotFoundTotal                = "prometheus_tsdb_head_series_not_found_total"
	prometheusTsdbHeadSeriesRemovedTotal                 = "prometheus_tsdb_head_series_removed_total"
	prometheusTsdbHeadTruncationsFailedTotal             = "prometheus_tsdb_head_truncations_failed_total"
	prometheusTsdbHeadTruncationsTotal                   = "prometheus_tsdb_head_truncations_total"
	prometheusTsdbLowestTimestamp                        = "prometheus_tsdb_lowest_timestamp"
	prometheusTsdbReloadsFailuresTotal                   = "prometheus_tsdb_reloads_failures_total"
	prometheusTsdbReloadsTotal                           = "prometheus_tsdb_reloads_total"
	prometheusTsdbRetentionCutoffsFailuresTotal          = "prometheus_tsdb_retention_cutoffs_failures_total"
	prometheusTsdbRetentionCutoffsTotal                  = "prometheus_tsdb_retention_cutoffs_total"
	prometheusTsdbSymbolTableSizeBytes                   = "prometheus_tsdb_symbol_table_size_bytes"
	prometheusTsdbTombstoneCleanupSeconds                = "prometheus_tsdb_tombstone_cleanup_seconds"
	prometheusTsdbTombstoneCleanupSecondsBucket          = "prometheus_tsdb_tombstone_cleanup_seconds_bucket"
	prometheusTsdbTombstoneCleanupSecondsCount           = "prometheus_tsdb_tombstone_cleanup_seconds_count"
	prometheusTsdbWalCompletedPagesTotal                 = "prometheus_tsdb_wal_completed_pages_total"
	prometheusTsdbWalFsyncDurationSeconds                = "prometheus_tsdb_wal_fsync_duration_seconds"
	prometheusTsdbWalFsyncDurationSecondsCount           = "prometheus_tsdb_wal_fsync_duration_seconds_count"
	prometheusTsdbWalPageFlushesTotal                    = "prometheus_tsdb_wal_page_flushes_total"
	prometheusTsdbWalTruncateDurationSeconds             = "prometheus_tsdb_wal_truncate_duration_seconds"
	prometheusTsdbWalTruncateDurationSecondsCount        = "prometheus_tsdb_wal_truncate_duration_seconds_count"
	prometheusTsdbWalTruncationsFailedTotal              = "prometheus_tsdb_wal_truncations_failed_total"
	prometheusTsdbWalTruncationsTotal                    = "prometheus_tsdb_wal_truncations_total"
	promhttpMetricHandlerRequestsInFlight                = "promhttp_metric_handler_requests_in_flight"
	promhttpMetricHandlerRequestsTotal                   = "promhttp_metric_handler_requests_total"
)

var metricSet = map[string]monitors.MetricInfo{
	netConntrackDialerConnAttemptedTotal:                 {Type: datapoint.Counter},
	netConntrackDialerConnClosedTotal:                    {Type: datapoint.Counter},
	netConntrackDialerConnEstablishedTotal:               {Type: datapoint.Counter},
	netConntrackDialerConnFailedTotal:                    {Type: datapoint.Counter},
	netConntrackListenerConnAcceptedTotal:                {Type: datapoint.Counter},
	netConntrackListenerConnClosedTotal:                  {Type: datapoint.Counter},
	prometheusAPIRemoteReadQueries:                       {Type: datapoint.Gauge},
	prometheusBuildInfo:                                  {Type: datapoint.Gauge},
	prometheusConfigLastReloadSuccessTimestampSeconds:    {Type: datapoint.Gauge},
	prometheusConfigLastReloadSuccessful:                 {Type: datapoint.Gauge},
	prometheusEngineQueries:                              {Type: datapoint.Gauge},
	prometheusEngineQueriesConcurrentMax:                 {Type: datapoint.Gauge},
	prometheusEngineQueryDurationSeconds:                 {Type: datapoint.Counter},
	prometheusEngineQueryDurationSecondsCount:            {Type: datapoint.Counter},
	prometheusHTTPRequestDurationSeconds:                 {Type: datapoint.Counter},
	prometheusHTTPRequestDurationSecondsBucket:           {Type: datapoint.Counter},
	prometheusHTTPRequestDurationSecondsCount:            {Type: datapoint.Counter},
	prometheusHTTPResponseSizeBytes:                      {Type: datapoint.Counter},
	prometheusHTTPResponseSizeBytesBucket:                {Type: datapoint.Counter},
	prometheusHTTPResponseSizeBytesCount:                 {Type: datapoint.Counter},
	prometheusNotificationsAlertmanagersDiscovered:       {Type: datapoint.Gauge},
	prometheusNotificationsDroppedTotal:                  {Type: datapoint.Counter},
	prometheusNotificationsQueueCapacity:                 {Type: datapoint.Gauge},
	prometheusNotificationsQueueLength:                   {Type: datapoint.Gauge},
	prometheusRuleEvaluationDurationSeconds:              {Type: datapoint.Counter},
	prometheusRuleEvaluationDurationSecondsCount:         {Type: datapoint.Counter},
	prometheusRuleEvaluationFailuresTotal:                {Type: datapoint.Counter},
	prometheusRuleGroupDurationSeconds:                   {Type: datapoint.Counter},
	prometheusRuleGroupDurationSecondsCount:              {Type: datapoint.Counter},
	prometheusRuleGroupIntervalSeconds:                   {Type: datapoint.Gauge},
	prometheusRuleGroupIterationsMissedTotal:             {Type: datapoint.Counter},
	prometheusRuleGroupIterationsTotal:                   {Type: datapoint.Counter},
	prometheusRuleGroupLastDurationSeconds:               {Type: datapoint.Gauge},
	prometheusSdAzureRefreshDurationSeconds:              {Type: datapoint.Counter},
	prometheusSdAzureRefreshDurationSecondsCount:         {Type: datapoint.Counter},
	prometheusSdAzureRefreshFailuresTotal:                {Type: datapoint.Counter},
	prometheusSdConfigsFailedTotal:                       {Type: datapoint.Counter},
	prometheusSdConsulRPCDurationSeconds:                 {Type: datapoint.Counter},
	prometheusSdConsulRPCDurationSecondsCount:            {Type: datapoint.Counter},
	prometheusSdConsulRPCFailuresTotal:                   {Type: datapoint.Counter},
	prometheusSdDiscoveredTargets:                        {Type: datapoint.Gauge},
	prometheusSdDNSLookupFailuresTotal:                   {Type: datapoint.Counter},
	prometheusSdDNSLookupsTotal:                          {Type: datapoint.Counter},
	prometheusSdEc2RefreshDurationSeconds:                {Type: datapoint.Counter},
	prometheusSdEc2RefreshDurationSecondsCount:           {Type: datapoint.Counter},
	prometheusSdEc2RefreshFailuresTotal:                  {Type: datapoint.Counter},
	prometheusSdFileReadErrorsTotal:                      {Type: datapoint.Counter},
	prometheusSdFileScanDurationSeconds:                  {Type: datapoint.Counter},
	prometheusSdFileScanDurationSecondsCount:             {Type: datapoint.Counter},
	prometheusSdGceRefreshDuration:                       {Type: datapoint.Counter},
	prometheusSdGceRefreshDurationCount:                  {Type: datapoint.Counter},
	prometheusSdGceRefreshFailuresTotal:                  {Type: datapoint.Counter},
	prometheusSdKubernetesCacheLastResourceVersion:       {Type: datapoint.Gauge},
	prometheusSdKubernetesCacheListDurationSeconds:       {Type: datapoint.Counter},
	prometheusSdKubernetesCacheListDurationSecondsCount:  {Type: datapoint.Counter},
	prometheusSdKubernetesCacheListItems:                 {Type: datapoint.Counter},
	prometheusSdKubernetesCacheListItemsCount:            {Type: datapoint.Counter},
	prometheusSdKubernetesCacheListTotal:                 {Type: datapoint.Counter},
	prometheusSdKubernetesCacheShortWatchesTotal:         {Type: datapoint.Counter},
	prometheusSdKubernetesCacheWatchDurationSeconds:      {Type: datapoint.Counter},
	prometheusSdKubernetesCacheWatchDurationSecondsCount: {Type: datapoint.Counter},
	prometheusSdKubernetesCacheWatchEvents:               {Type: datapoint.Counter},
	prometheusSdKubernetesCacheWatchEventsCount:          {Type: datapoint.Counter},
	prometheusSdKubernetesCacheWatchesTotal:              {Type: datapoint.Counter},
	prometheusSdKubernetesEventsTotal:                    {Type: datapoint.Counter},
	prometheusSdMarathonRefreshDurationSeconds:           {Type: datapoint.Counter},
	prometheusSdMarathonRefreshDurationSecondsCount:      {Type: datapoint.Counter},
	prometheusSdMarathonRefreshFailuresTotal:             {Type: datapoint.Counter},
	prometheusSdOpenstackRefreshDurationSeconds:          {Type: datapoint.Counter},
	prometheusSdOpenstackRefreshDurationSecondsCount:     {Type: datapoint.Counter},
	prometheusSdOpenstackRefreshFailuresTotal:            {Type: datapoint.Counter},
	prometheusSdReceivedUpdatesTotal:                     {Type: datapoint.Counter},
	prometheusSdTritonRefreshDurationSeconds:             {Type: datapoint.Counter},
	prometheusSdTritonRefreshDurationSecondsCount:        {Type: datapoint.Counter},
	prometheusSdTritonRefreshFailuresTotal:               {Type: datapoint.Counter},
	prometheusSdUpdatesDelayedTotal:                      {Type: datapoint.Counter},
	prometheusSdUpdatesTotal:                             {Type: datapoint.Counter},
	prometheusTargetIntervalLengthSeconds:                {Type: datapoint.Counter},
	prometheusTargetIntervalLengthSecondsCount:           {Type: datapoint.Counter},
	prometheusTargetScrapePoolSyncTotal:                  {Type: datapoint.Counter},
	prometheusTargetScrapesExceededSampleLimitTotal:      {Type: datapoint.Counter},
	prometheusTargetScrapesSampleDuplicateTimestampTotal: {Type: datapoint.Counter},
	prometheusTargetScrapesSampleOutOfBoundsTotal:        {Type: datapoint.Counter},
	prometheusTargetScrapesSampleOutOfOrderTotal:         {Type: datapoint.Counter},
	prometheusTargetSyncLengthSeconds:                    {Type: datapoint.Counter},
	prometheusTargetSyncLengthSecondsCount:               {Type: datapoint.Counter},
	prometheusTreecacheWatcherGoroutines:                 {Type: datapoint.Gauge},
	prometheusTreecacheZookeeperFailuresTotal:            {Type: datapoint.Counter},
	prometheusTsdbBlocksLoaded:                           {Type: datapoint.Gauge},
	prometheusTsdbCheckpointCreationsFailedTotal:         {Type: datapoint.Counter},
	prometheusTsdbCheckpointCreationsTotal:               {Type: datapoint.Counter},
	prometheusTsdbCheckpointDeletionsFailedTotal:         {Type: datapoint.Counter},
	prometheusTsdbCheckpointDeletionsTotal:               {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkRangeSeconds:            {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkRangeSecondsBucket:      {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkRangeSecondsCount:       {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkSamples:                 {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkSamplesBucket:           {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkSamplesCount:            {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkSizeBytes:               {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkSizeBytesBucket:         {Type: datapoint.Counter},
	prometheusTsdbCompactionChunkSizeBytesCount:          {Type: datapoint.Counter},
	prometheusTsdbCompactionDurationSeconds:              {Type: datapoint.Counter},
	prometheusTsdbCompactionDurationSecondsBucket:        {Type: datapoint.Counter},
	prometheusTsdbCompactionDurationSecondsCount:         {Type: datapoint.Counter},
	prometheusTsdbCompactionsFailedTotal:                 {Type: datapoint.Counter},
	prometheusTsdbCompactionsTotal:                       {Type: datapoint.Counter},
	prometheusTsdbCompactionsTriggeredTotal:              {Type: datapoint.Counter},
	prometheusTsdbHeadActiveAppenders:                    {Type: datapoint.Gauge},
	prometheusTsdbHeadChunks:                             {Type: datapoint.Gauge},
	prometheusTsdbHeadChunksCreatedTotal:                 {Type: datapoint.Counter},
	prometheusTsdbHeadChunksRemovedTotal:                 {Type: datapoint.Counter},
	prometheusTsdbHeadGcDurationSeconds:                  {Type: datapoint.Counter},
	prometheusTsdbHeadGcDurationSecondsCount:             {Type: datapoint.Counter},
	prometheusTsdbHeadMaxTime:                            {Type: datapoint.Gauge},
	prometheusTsdbHeadMinTime:                            {Type: datapoint.Gauge},
	prometheusTsdbHeadSamplesAppendedTotal:               {Type: datapoint.Counter},
	prometheusTsdbHeadSeries:                             {Type: datapoint.Gauge},
	prometheusTsdbHeadSeriesCreatedTotal:                 {Type: datapoint.Counter},
	prometheusTsdbHeadSeriesNotFoundTotal:                {Type: datapoint.Counter},
	prometheusTsdbHeadSeriesRemovedTotal:                 {Type: datapoint.Counter},
	prometheusTsdbHeadTruncationsFailedTotal:             {Type: datapoint.Counter},
	prometheusTsdbHeadTruncationsTotal:                   {Type: datapoint.Counter},
	prometheusTsdbLowestTimestamp:                        {Type: datapoint.Gauge},
	prometheusTsdbReloadsFailuresTotal:                   {Type: datapoint.Counter},
	prometheusTsdbReloadsTotal:                           {Type: datapoint.Counter},
	prometheusTsdbRetentionCutoffsFailuresTotal:          {Type: datapoint.Counter},
	prometheusTsdbRetentionCutoffsTotal:                  {Type: datapoint.Counter},
	prometheusTsdbSymbolTableSizeBytes:                   {Type: datapoint.Gauge},
	prometheusTsdbTombstoneCleanupSeconds:                {Type: datapoint.Counter},
	prometheusTsdbTombstoneCleanupSecondsBucket:          {Type: datapoint.Counter},
	prometheusTsdbTombstoneCleanupSecondsCount:           {Type: datapoint.Counter},
	prometheusTsdbWalCompletedPagesTotal:                 {Type: datapoint.Counter},
	prometheusTsdbWalFsyncDurationSeconds:                {Type: datapoint.Counter},
	prometheusTsdbWalFsyncDurationSecondsCount:           {Type: datapoint.Counter},
	prometheusTsdbWalPageFlushesTotal:                    {Type: datapoint.Counter},
	prometheusTsdbWalTruncateDurationSeconds:             {Type: datapoint.Counter},
	prometheusTsdbWalTruncateDurationSecondsCount:        {Type: datapoint.Counter},
	prometheusTsdbWalTruncationsFailedTotal:              {Type: datapoint.Counter},
	prometheusTsdbWalTruncationsTotal:                    {Type: datapoint.Counter},
	promhttpMetricHandlerRequestsInFlight:                {Type: datapoint.Gauge},
	promhttpMetricHandlerRequestsTotal:                   {Type: datapoint.Counter},
}

var defaultMetrics = map[string]bool{}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "prometheus/prometheus",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         true,
}
