[install]
state = enabled

[ui]
is_visible = 0
show_in_nav = false
label = Splunk Connect for OTLP

[package]
id = splunk-connect-for-otlp

[launcher]
description = Run an OTLP endpoint to collect data
version = 0.4.1

[id]
name = splunk-connect-for-otlp
version = 0.4.1
