[splunk-connect-for-otlp]
# Required parameters for the application to function:
start_by_shell = false
interval = 0
sourcetype=splunk-connect-for-otlp
# User configuration
grpc_port = 4317
http_port = 4318
listen_address = 0.0.0.0

# WARNING: If SSL is enabled, serverCert and serverKey are required, otherwise TA will fail on start.
# WARNING: Disabling SSL is not recommended for production environments, use it only for prototyping.
enableSSL = 1
serverCert =
serverKey =
