[script:restproxy_logs]
match = /v1/logs
driver = restproxy
script = restproxy
scripttype = persist
requireAuthentication = false
output_modes = json
passHttpHeaders = true
passHttpCookies = true
passPayload = base64

[script:restproxy_metrics]
match = /v1/metrics
driver = restproxy
script = restproxy
scripttype = persist
requireAuthentication = false
output_modes = json
passHttpHeaders = true
passHttpCookies = true
passPayload = base64

[script:restproxy_traces]
match = /v1/traces
driver = restproxy
script = restproxy
scripttype = persist
requireAuthentication = false
output_modes = json
passHttpHeaders = true
passHttpCookies = true
passPayload = base64
