# Sample systemd environment file for passing environment variables to the splunk-otel-collector service and the
# collector configuration file.

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile= for general information about
# systemd environment files, supported syntax, and limitations.

# To use this file:
# 1. Add/Update the environment variables below.
# 2. Save/Rename this file as "/etc/otel/script/splunk-otel-script.conf".
# 3. Run the following command to restart the service and apply the changes:
#      sudo systemctl restart splunk-otel-script.service

SCRIPT_JOBS_FOLDER=/etc/otel/script/jobs/