#!/bin/sh

# Copyright Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The interpreter on all binary files will be set to the bundled interpreter.

set -eu

# The final place where the files will live
root=${1}
# The place where the files currently live when this script is run
tmproot=${2-$root}
interpreter="${root%/}/bin/ld-linux.so"

echo "Setting interpreter on ${tmproot%/}/bin/* to $interpreter"

for f in ${tmproot%/}/bin/* ${tmproot%/}/jre/bin/*; do
  ${tmproot%/}/bin/patchelf --set-interpreter $interpreter $f 2>/dev/null || true
done
