// Code generated by monitor-code-gen. DO NOT EDIT.

package vmem

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "vmem"

var groupSet = map[string]bool{}

const (
	vmpageSwapInPerSecond      = "vmpage.swap.in_per_second"
	vmpageSwapOutPerSecond     = "vmpage.swap.out_per_second"
	vmpageSwapTotalPerSecond   = "vmpage.swap.total.per_second"
	vmpageFaultsMajflt         = "vmpage_faults.majflt"
	vmpageFaultsMinflt         = "vmpage_faults.minflt"
	vmpageIoMemoryIn           = "vmpage_io.memory.in"
	vmpageIoMemoryOut          = "vmpage_io.memory.out"
	vmpageIoSwapIn             = "vmpage_io.swap.in"
	vmpageIoSwapOut            = "vmpage_io.swap.out"
	vmpageNumberFreePages      = "vmpage_number.free_pages"
	vmpageNumberMapped         = "vmpage_number.mapped"
	vmpageNumberShmemPmdmapped = "vmpage_number.shmem_pmdmapped"
)

var metricSet = map[string]monitors.MetricInfo{
	vmpageSwapInPerSecond:      {Type: datapoint.Gauge},
	vmpageSwapOutPerSecond:     {Type: datapoint.Gauge},
	vmpageSwapTotalPerSecond:   {Type: datapoint.Gauge},
	vmpageFaultsMajflt:         {Type: datapoint.Counter},
	vmpageFaultsMinflt:         {Type: datapoint.Counter},
	vmpageIoMemoryIn:           {Type: datapoint.Counter},
	vmpageIoMemoryOut:          {Type: datapoint.Counter},
	vmpageIoSwapIn:             {Type: datapoint.Counter},
	vmpageIoSwapOut:            {Type: datapoint.Counter},
	vmpageNumberFreePages:      {Type: datapoint.Gauge},
	vmpageNumberMapped:         {Type: datapoint.Gauge},
	vmpageNumberShmemPmdmapped: {Type: datapoint.Gauge},
}

var defaultMetrics = map[string]bool{
	vmpageIoSwapIn:  true,
	vmpageIoSwapOut: true,
}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "vmem",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
