---
- name: Verify auto-instrumentation scenario
  hosts: all
  gather_facts: false
  vars:
    expected_instrumentation_sdks:
      - java
      - dotnet
    expected_instrumentation_systemd: false
    expected_custom_instrumentation: false
    expected_custom_preload: false
  tasks:
    - name: Verify OpenTelemetry injector configuration
      ansible.builtin.include_tasks: ../shared/verify_instrumentation.yml
