---
# Install Splunk OpenTelemetry Auto Instrumentation with zypper package manager

- name: Install Splunk OpenTelemetry Auto Instrumentation via zypper package manager
  community.general.zypper:
    name: "splunk-otel-auto-instrumentation{% if splunk_otel_auto_instrumentation_version != 'latest' %}\
      -{{ splunk_otel_auto_instrumentation_version }}{% endif %}"
    state: "{% if splunk_otel_auto_instrumentation_version != 'latest' %}present{% else %}latest{% endif %}"
    oldpackage: yes
    update_cache: yes
  register: zypper_instrumentation_package
  when: not local_artifact_testing_enabled

- name: Copy Splunk OpenTelemetry Auto Instrumentation RPM artifact to remote machine
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/otel/
    mode: '644'
  loop: "{{ query('ansible.builtin.fileglob', auto_instrumentation_rpm_artifact_pattern) }}"
  vars:
    auto_instrumentation_rpm_artifact_pattern: >-
      /tmp/splunk-otel-auto-instrumentation-{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}-rpm/*.rpm
  register: local_zypper_instrumentation_artifact
  when: local_artifact_testing_enabled

- name: Ensure local Splunk OpenTelemetry Auto Instrumentation RPM artifact was copied
  ansible.builtin.assert:
    that:
      - local_zypper_instrumentation_artifact.results | length == 1
    fail_msg: Failed to find exactly one local Splunk OpenTelemetry Auto Instrumentation RPM artifact.
  when: local_artifact_testing_enabled

- name: Install Splunk OpenTelemetry Auto Instrumentation via local RPM artifact
  community.general.zypper:
    name: "{{ local_zypper_instrumentation_artifact.results[0].dest }}"
    disable_gpg_check: true
  register: zypper_instrumentation_package
  when: local_artifact_testing_enabled
