// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for nutanix metrics.
type MetricsConfig struct {
	NutanixClusterCount                                MetricConfig `mapstructure:"nutanix.cluster.count"`
	NutanixClusterInfo                                 MetricConfig `mapstructure:"nutanix.cluster.info"`
	NutanixClusterStat                                 MetricConfig `mapstructure:"nutanix.cluster.stat"`
	NutanixDataProtectionProtectedVMCount              MetricConfig `mapstructure:"nutanix.data_protection.protected_vm.count"`
	NutanixDataProtectionProtectionPolicyCount         MetricConfig `mapstructure:"nutanix.data_protection.protection_policy.count"`
	NutanixDataProtectionProtectionPolicyScheduleCount MetricConfig `mapstructure:"nutanix.data_protection.protection_policy_schedule.count"`
	NutanixDataProtectionRecoveryPointCount            MetricConfig `mapstructure:"nutanix.data_protection.recovery_point.count"`
	NutanixDiskCount                                   MetricConfig `mapstructure:"nutanix.disk.count"`
	NutanixDiskStat                                    MetricConfig `mapstructure:"nutanix.disk.stat"`
	NutanixFilesAntivirusServerCount                   MetricConfig `mapstructure:"nutanix.files.antivirus_server.count"`
	NutanixFilesAntivirusServerStat                    MetricConfig `mapstructure:"nutanix.files.antivirus_server.stat"`
	NutanixFilesFileServerCount                        MetricConfig `mapstructure:"nutanix.files.file_server.count"`
	NutanixFilesFileServerStat                         MetricConfig `mapstructure:"nutanix.files.file_server.stat"`
	NutanixFilesMountTargetCount                       MetricConfig `mapstructure:"nutanix.files.mount_target.count"`
	NutanixFilesMountTargetStat                        MetricConfig `mapstructure:"nutanix.files.mount_target.stat"`
	NutanixFilesUnifiedNamespaceCount                  MetricConfig `mapstructure:"nutanix.files.unified_namespace.count"`
	NutanixHostCount                                   MetricConfig `mapstructure:"nutanix.host.count"`
	NutanixHostStat                                    MetricConfig `mapstructure:"nutanix.host.stat"`
	NutanixMicrosegAddressGroupCount                   MetricConfig `mapstructure:"nutanix.microseg.address_group.count"`
	NutanixMicrosegNetworkSecurityPolicyCount          MetricConfig `mapstructure:"nutanix.microseg.network_security_policy.count"`
	NutanixMicrosegServiceGroupCount                   MetricConfig `mapstructure:"nutanix.microseg.service_group.count"`
	NutanixMonitoringAlertCount                        MetricConfig `mapstructure:"nutanix.monitoring.alert.count"`
	NutanixNetworkingBgpSessionCount                   MetricConfig `mapstructure:"nutanix.networking.bgp_session.count"`
	NutanixNetworkingGatewayCount                      MetricConfig `mapstructure:"nutanix.networking.gateway.count"`
	NutanixNetworkingLayer2StretchCount                MetricConfig `mapstructure:"nutanix.networking.layer2_stretch.count"`
	NutanixNetworkingLayer2StretchStat                 MetricConfig `mapstructure:"nutanix.networking.layer2_stretch.stat"`
	NutanixNetworkingNetworkControllerCount            MetricConfig `mapstructure:"nutanix.networking.network_controller.count"`
	NutanixNetworkingRoutingPolicyCount                MetricConfig `mapstructure:"nutanix.networking.routing_policy.count"`
	NutanixNetworkingTrafficMirrorCount                MetricConfig `mapstructure:"nutanix.networking.traffic_mirror.count"`
	NutanixNetworkingTrafficMirrorStat                 MetricConfig `mapstructure:"nutanix.networking.traffic_mirror.stat"`
	NutanixNetworkingUplinkBondCount                   MetricConfig `mapstructure:"nutanix.networking.uplink_bond.count"`
	NutanixNetworkingVirtualSwitchCount                MetricConfig `mapstructure:"nutanix.networking.virtual_switch.count"`
	NutanixNetworkingVpcCount                          MetricConfig `mapstructure:"nutanix.networking.vpc.count"`
	NutanixNetworkingVpcExternalSubnetStat             MetricConfig `mapstructure:"nutanix.networking.vpc.external_subnet.stat"`
	NutanixNetworkingVpnConnectionCount                MetricConfig `mapstructure:"nutanix.networking.vpn_connection.count"`
	NutanixNetworkingVpnConnectionStat                 MetricConfig `mapstructure:"nutanix.networking.vpn_connection.stat"`
	NutanixObjectsObjectStoreCount                     MetricConfig `mapstructure:"nutanix.objects.object_store.count"`
	NutanixObjectsObjectStoreStat                      MetricConfig `mapstructure:"nutanix.objects.object_store.stat"`
	NutanixPrismCategoryCount                          MetricConfig `mapstructure:"nutanix.prism.category.count"`
	NutanixPrismCategoryKeyCount                       MetricConfig `mapstructure:"nutanix.prism.category_key.count"`
	NutanixPrismTaskCount                              MetricConfig `mapstructure:"nutanix.prism.task.count"`
	NutanixStorageContainerCount                       MetricConfig `mapstructure:"nutanix.storage.container.count"`
	NutanixStorageContainerStat                        MetricConfig `mapstructure:"nutanix.storage.container.stat"`
	NutanixSubnetCount                                 MetricConfig `mapstructure:"nutanix.subnet.count"`
	NutanixVMCount                                     MetricConfig `mapstructure:"nutanix.vm.count"`
	NutanixVMDiskCount                                 MetricConfig `mapstructure:"nutanix.vm.disk.count"`
	NutanixVMMemoryAssigned                            MetricConfig `mapstructure:"nutanix.vm.memory.assigned"`
	NutanixVMNicsCount                                 MetricConfig `mapstructure:"nutanix.vm.nics.count"`
	NutanixVMStat                                      MetricConfig `mapstructure:"nutanix.vm.stat"`
	NutanixVMVcpuCount                                 MetricConfig `mapstructure:"nutanix.vm.vcpu.count"`
	NutanixVolumeGroupCount                            MetricConfig `mapstructure:"nutanix.volume_group.count"`
	NutanixVolumeGroupStat                             MetricConfig `mapstructure:"nutanix.volume_group.stat"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NutanixClusterCount: MetricConfig{
			Enabled: true,
		},
		NutanixClusterInfo: MetricConfig{
			Enabled: true,
		},
		NutanixClusterStat: MetricConfig{
			Enabled: true,
		},
		NutanixDataProtectionProtectedVMCount: MetricConfig{
			Enabled: true,
		},
		NutanixDataProtectionProtectionPolicyCount: MetricConfig{
			Enabled: true,
		},
		NutanixDataProtectionProtectionPolicyScheduleCount: MetricConfig{
			Enabled: true,
		},
		NutanixDataProtectionRecoveryPointCount: MetricConfig{
			Enabled: true,
		},
		NutanixDiskCount: MetricConfig{
			Enabled: true,
		},
		NutanixDiskStat: MetricConfig{
			Enabled: true,
		},
		NutanixFilesAntivirusServerCount: MetricConfig{
			Enabled: true,
		},
		NutanixFilesAntivirusServerStat: MetricConfig{
			Enabled: true,
		},
		NutanixFilesFileServerCount: MetricConfig{
			Enabled: true,
		},
		NutanixFilesFileServerStat: MetricConfig{
			Enabled: true,
		},
		NutanixFilesMountTargetCount: MetricConfig{
			Enabled: true,
		},
		NutanixFilesMountTargetStat: MetricConfig{
			Enabled: true,
		},
		NutanixFilesUnifiedNamespaceCount: MetricConfig{
			Enabled: true,
		},
		NutanixHostCount: MetricConfig{
			Enabled: true,
		},
		NutanixHostStat: MetricConfig{
			Enabled: true,
		},
		NutanixMicrosegAddressGroupCount: MetricConfig{
			Enabled: true,
		},
		NutanixMicrosegNetworkSecurityPolicyCount: MetricConfig{
			Enabled: true,
		},
		NutanixMicrosegServiceGroupCount: MetricConfig{
			Enabled: true,
		},
		NutanixMonitoringAlertCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingBgpSessionCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingGatewayCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingLayer2StretchCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingLayer2StretchStat: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingNetworkControllerCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingRoutingPolicyCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingTrafficMirrorCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingTrafficMirrorStat: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingUplinkBondCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingVirtualSwitchCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingVpcCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingVpcExternalSubnetStat: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingVpnConnectionCount: MetricConfig{
			Enabled: true,
		},
		NutanixNetworkingVpnConnectionStat: MetricConfig{
			Enabled: true,
		},
		NutanixObjectsObjectStoreCount: MetricConfig{
			Enabled: true,
		},
		NutanixObjectsObjectStoreStat: MetricConfig{
			Enabled: true,
		},
		NutanixPrismCategoryCount: MetricConfig{
			Enabled: true,
		},
		NutanixPrismCategoryKeyCount: MetricConfig{
			Enabled: true,
		},
		NutanixPrismTaskCount: MetricConfig{
			Enabled: true,
		},
		NutanixStorageContainerCount: MetricConfig{
			Enabled: true,
		},
		NutanixStorageContainerStat: MetricConfig{
			Enabled: true,
		},
		NutanixSubnetCount: MetricConfig{
			Enabled: true,
		},
		NutanixVMCount: MetricConfig{
			Enabled: true,
		},
		NutanixVMDiskCount: MetricConfig{
			Enabled: true,
		},
		NutanixVMMemoryAssigned: MetricConfig{
			Enabled: true,
		},
		NutanixVMNicsCount: MetricConfig{
			Enabled: true,
		},
		NutanixVMStat: MetricConfig{
			Enabled: true,
		},
		NutanixVMVcpuCount: MetricConfig{
			Enabled: true,
		},
		NutanixVolumeGroupCount: MetricConfig{
			Enabled: true,
		},
		NutanixVolumeGroupStat: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for nutanix resource attributes.
type ResourceAttributesConfig struct {
	NutanixPrismAPIVersion ResourceAttributeConfig `mapstructure:"nutanix.prism.api.version"`
	ServerAddress          ResourceAttributeConfig `mapstructure:"server.address"`
	ServerPort             ResourceAttributeConfig `mapstructure:"server.port"`
	ServiceInstanceID      ResourceAttributeConfig `mapstructure:"service.instance.id"`
	ServiceName            ResourceAttributeConfig `mapstructure:"service.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		NutanixPrismAPIVersion: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerAddress: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerPort: ResourceAttributeConfig{
			Enabled: true,
		},
		ServiceInstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
		ServiceName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for nutanix metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
