// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for nutanix metrics.
type MetricsConfig struct {
	NutanixClusterInfo           MetricConfig `mapstructure:"nutanix.cluster.info"`
	NutanixClusterStat           MetricConfig `mapstructure:"nutanix.cluster.stat"`
	NutanixHostStat              MetricConfig `mapstructure:"nutanix.host.stat"`
	NutanixStorageContainerCount MetricConfig `mapstructure:"nutanix.storage.container.count"`
	NutanixStorageContainerStat  MetricConfig `mapstructure:"nutanix.storage.container.stat"`
	NutanixVMCount               MetricConfig `mapstructure:"nutanix.vm.count"`
	NutanixVMDiskCount           MetricConfig `mapstructure:"nutanix.vm.disk.count"`
	NutanixVMMemoryAssigned      MetricConfig `mapstructure:"nutanix.vm.memory.assigned"`
	NutanixVMNicCount            MetricConfig `mapstructure:"nutanix.vm.nic.count"`
	NutanixVMStat                MetricConfig `mapstructure:"nutanix.vm.stat"`
	NutanixVMVcpuCount           MetricConfig `mapstructure:"nutanix.vm.vcpu.count"`
	NutanixVolumeGroupCount      MetricConfig `mapstructure:"nutanix.volume_group.count"`
	NutanixVolumeGroupStat       MetricConfig `mapstructure:"nutanix.volume_group.stat"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NutanixClusterInfo: MetricConfig{
			Enabled: true,
		},
		NutanixClusterStat: MetricConfig{
			Enabled: true,
		},
		NutanixHostStat: MetricConfig{
			Enabled: true,
		},
		NutanixStorageContainerCount: MetricConfig{
			Enabled: true,
		},
		NutanixStorageContainerStat: MetricConfig{
			Enabled: true,
		},
		NutanixVMCount: MetricConfig{
			Enabled: true,
		},
		NutanixVMDiskCount: MetricConfig{
			Enabled: true,
		},
		NutanixVMMemoryAssigned: MetricConfig{
			Enabled: true,
		},
		NutanixVMNicCount: MetricConfig{
			Enabled: true,
		},
		NutanixVMStat: MetricConfig{
			Enabled: true,
		},
		NutanixVMVcpuCount: MetricConfig{
			Enabled: true,
		},
		NutanixVolumeGroupCount: MetricConfig{
			Enabled: true,
		},
		NutanixVolumeGroupStat: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for nutanix resource attributes.
type ResourceAttributesConfig struct {
	NutanixPrismAPIVersion ResourceAttributeConfig `mapstructure:"nutanix.prism.api.version"`
	ServerAddress          ResourceAttributeConfig `mapstructure:"server.address"`
	ServerPort             ResourceAttributeConfig `mapstructure:"server.port"`
	ServiceInstanceID      ResourceAttributeConfig `mapstructure:"service.instance.id"`
	ServiceName            ResourceAttributeConfig `mapstructure:"service.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		NutanixPrismAPIVersion: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerAddress: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerPort: ResourceAttributeConfig{
			Enabled: true,
		},
		ServiceInstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
		ServiceName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for nutanix metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
