change_type: deprecation
component: configuration
note: Deprecate `/etc/otel/collector/otlp_config_linux.yaml` and warn users to migrate to `/etc/otel/collector/agent_config.yaml`.
issues: [7729]
subtext: Set `SPLUNK_LISTEN_INTERFACE=0.0.0.0` when migrating if receivers need to listen outside the container.
