change_type: deprecation
component: configuration
note: The default config `/etc/otel/collector/otlp_config_linux.yaml` is now deprecated and will be removed in a future release.
issues: [7848]
subtext: Migrate to `/etc/otel/collector/agent_config.yaml`. Set `SPLUNK_LISTEN_INTERFACE=0.0.0.0` when migrating if receivers need to listen outside the container.
