change_type: breaking
component: receiver/lightprometheus
note: Remove the deprecated `lightprometheus` receiver.
issues: [8086]
subtext: |
  Use the `prometheus` or `prometheus_simple` receiver instead.
