name: Check pinned actions

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-pinned-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check all actions are SHA-pinned
        shell: bash
        run: ./.github/scripts/check-pinned-actions.sh
