name: chef-test

# Only run tests if there are relevant changes
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/chef-test.yml'
      - 'deployments/chef/**'
      - 'packaging/msi/**'
      - '!**.md'
  pull_request:
    paths:
      - '.github/workflows/chef-test.yml'
      - 'deployments/chef/**'
      - 'packaging/msi/**'
      - '!**.md'
  schedule:
    - cron: '0 0 * * 2,5' # Every Tuesday and Friday at midnight UTC

env:
  # EOL REFERENCE: https://endoflife.date/chef-workstation
  CHEF_VERSION: "25.12.1102"
  CHEF_LICENSE: accept

jobs:
  chef-kitchen-windows:
    runs-on: windows-2025
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install chef
        uses: actionshub/chef-install@f3b35943a257c25f3ca69e3b773fa4e0e99b58d6 # 6.0.0
        with:
          version: "25.12.1102"
