name: installer-script-test

# Only run tests for main branch or if the PR has relevant changes
on: 
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/installer-script-test.yml'
      - 'packaging/installer/install.sh'
      - 'packaging/tests/instrumentation/**'
      - 'packaging/tests/custom-config.yaml'
      - 'packaging/tests/images/**'
      - 'tests/installer/**'
      - 'tests/testutils/**'
      - 'tests/go.mod'
      - 'tests/go.sum'

concurrency:
  group: installer-script-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  installer-test-matrix:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get distros
        id: get-matrix
        run: |
          # create test matrix for distro images and archs
          dockerfiles=$(find packaging/tests/images/deb/Dockerfile.* packaging/tests/images/rpm/Dockerfile.* | cut -d '.' -f2- | sort -u)
          if [ -z "$dockerfiles" ]; then
            echo "Failed to get dockerfiles from packaging/tests/images!" >&2
            exit 1
          fi
          distro=$(for d in $dockerfiles; do echo -n "\"$d\","; done)
          arch='"amd64","arm64"'
          instrumentation='"none","preload","systemd"'
          matrix="{\"DISTRO\": [${distro%,}], \"ARCH\": [${arch}], \"INSTRUMENTATION\": [${instrumentation}]}"
          echo "$matrix" | jq
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}

  linux-installer-script-test:
    runs-on: ubuntu-24.04${{ matrix.ARCH == 'arm64' && '-arm' || '' }}
    timeout-minutes: 90
    needs: installer-test-matrix
    strategy:
      matrix: ${{ fromJSON(needs.installer-test-matrix.outputs.matrix) }}
      fail-fast: false
    env:
      GO_VERSION: '1.26.4'
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: 'tests/go.sum'

      - name: Test installer script
        id: go-test
        continue-on-error: true
        working-directory: tests
        run: |
          distro="${{ matrix.DISTRO }}"
          if [[ "${{ matrix.INSTRUMENTATION }}" = "none" ]]; then
            go test -tags integration -count=1 -timeout 85m ./installer \
              -run "^TestInstaller(Default|Custom|WithOBI)$/${distro}/${{ matrix.ARCH }}"
            go test -tags integration -count=1 -timeout 85m ./installer \
              -run "^TestInstallerSplunkPlatformValidation$/.*/${distro}/${{ matrix.ARCH }}"
          else
            go test -tags integration -count=1 -timeout 85m ./installer \
              -run "^TestInstallerWithInstrumentation(Default|Custom)$/${distro}/${{ matrix.ARCH }}/${{ matrix.INSTRUMENTATION }}"
          fi

      # networking, running systemd in containers, etc., can be flaky
      - name: Re-run failed tests
        if: ${{ steps.go-test.outcome == 'failure' }}
        working-directory: tests
        run: |
          distro="${{ matrix.DISTRO }}"
          if [[ "${{ matrix.INSTRUMENTATION }}" = "none" ]]; then
            go test -tags integration -count=1 -timeout 85m ./installer \
              -run "^TestInstaller(Default|Custom|WithOBI)$/${distro}/${{ matrix.ARCH }}"
            go test -tags integration -count=1 -timeout 85m ./installer \
              -run "^TestInstallerSplunkPlatformValidation$/.*/${distro}/${{ matrix.ARCH }}"
          else
            go test -tags integration -count=1 -timeout 85m ./installer \
              -run "^TestInstallerWithInstrumentation(Default|Custom)$/${distro}/${{ matrix.ARCH }}/${{ matrix.INSTRUMENTATION }}"
          fi
