name: compile

on:
  workflow_call:
    secrets:
      OTELCOL_PRIVATE_MODULES_USER:
        required: true
      OTELCOL_PRIVATE_MODULES_TOKEN:
        required: true
    inputs:
      SYS_BINARY:
        required: true
        type: string

env:
  GO_VERSION: 1.26.4

jobs:
  compile:
    name: compile
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-environment
        with:
          private-modules-user: ${{ secrets.OTELCOL_PRIVATE_MODULES_USER }}
          private-modules-token: ${{ secrets.OTELCOL_PRIVATE_MODULES_TOKEN }}

      - name: Build Collector
        run: |
          make ${{ inputs.SYS_BINARY }}

      - name: Uploading binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.SYS_BINARY }}
          path: |
            ./bin/*
