name: compile

on:
  workflow_call:
    inputs:
      SYS_BINARY:
        required: true
        type: string

env:
  GO_VERSION: 1.25.8

jobs:
  compile:
    name: compile
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-environment

      - name: Build Collector
        run: |
          make ${{ inputs.SYS_BINARY }}

      - name: Uploading binaries
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ inputs.SYS_BINARY }}
          path: |
            ./bin/*
