name: compile

on:
  workflow_call:
    inputs:
      SYS_BINARY:
        required: true
        type: string

env:
  GO_VERSION: 1.26.3

jobs:
  compile:
    name: compile
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-environment

      - name: Build Collector
        run: |
          make ${{ inputs.SYS_BINARY }}

      - name: Uploading binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.SYS_BINARY }}
          path: |
            ./bin/*
